export const items = [
    {
        id: 'id-1',
        name: 'Phone',
        price: '5000',
        url: 'https://content1.rozetka.com.ua/goods/images/preview/201819255.jpg',
        item: 'AA4',
        color: 'black',
    },
    {
        id: 'id-2',
        name: 'Headphone',
        price: '300',
        url: 'https://content1.rozetka.com.ua/goods/images/big/189634179.jpg',
        item: 'AB6',
        color: 'white',
    },
    {
        id: 'id-3',
        name: 'Laptop',
        price: '1000',
        url: 'https://content2.rozetka.com.ua/goods/images/big/194254717.jpg',
        item: 'CC8',
        color: 'gray',
    },
    {
        id: 'id-4',
        name: 'Lamp',
        price: '900',
        url: 'https://content2.rozetka.com.ua/goods/images/big/2405350.jpg',
        item: 'RS3',
        color: 'white',
    },
    {
        id: 'id-5',
        name: 'Coffee machine',
        price: '11000',
        url: 'https://content1.rozetka.com.ua/goods/images/big/56478475.jpg',
        item: 'P4',
        color: 'white',
    },
    {
        id: 'id-6',
        name: 'Refrigerator',
        price: '30000',
        url: 'https://content1.rozetka.com.ua/goods/images/big/184096517.jpg',
        item: 'BB6',
        color: 'white',
    },
    {
        id: 'id-7',
        name: 'Grill',
        price: '10000',
        url: 'https://content1.rozetka.com.ua/goods/images/big/16938086.jpg',
        item: 'FE18',
        color: 'silver',
    },
    {
        id: 'id-8',
        name: 'Camera',
        price: '800',
        url: 'https://content.rozetka.com.ua/goods/images/big/11959892.jpg',
        item: 'RS12',
        color: 'black',
    },
    {
        id: 'id-9',
        name: 'Headphone',
        price: '500',
        url: 'https://content1.rozetka.com.ua/goods/images/big/174532385.jpg',
        item: 'RF56',
        color: 'black',
    },
    {
        id: 'id-10',
        name: 'TV',
        price: '10000',
        url: 'https://content2.rozetka.com.ua/goods/images/big/174795929.jpg',
        item: 'AA5',
        color: 'black',
    },
];
