export const BOOK_ADDED_TO_CART = 'BOOK_ADDED_TO_CART';
export const BOOK_REMOVED_FROM_CART = 'BOOK_REMOVED_FROM_CART';
export const ALL_BOOKS_REMOVED_FROM_CART = 'ALL_BOOKS_REMOVED_FROM_CART';
export const INCREASE_BOOK_AMOUNT = 'INCREASE_BOOK_AMOUNT';
export const DECREASE_BOOK_AMOUNT = 'DECREASE_BOOK_AMOUNT';
