const uniqueRandom = require("unique-random");
const rand = uniqueRandom(0, 999999);

module.exports =  productsData = [
  {
    name: "A puppy called sparkle",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637360698/books/puppy-Sparkle_wu4rji.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 220,
    publisher: "Noicy Crow",
    shortDescription: "Jasmine falls in love at first sight with the little Golden Retriever puppy she rescues, but she knows she won't be able to keep Sparkle forever. Jasmine soon sees that the playful, friendly puppy is quick and eager to learn, and has an incredible sense of smell.",
    fullDescription: "<p>The twelfth in a fantastic series of animal stories for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon.</p><p>Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself… </p><p>Jasmine falls in love at first sight with the little Golden Retriever puppy she rescues, but she knows she won’t be able to keep Sparkle forever. Jasmine soon sees that the playful, friendly puppy is quick and eager to learn, and has an incredible sense of smell. When a new girl starts at Jasmine’s school, bringing her medical assistance dog with her, Jasmine starts to wonder. Could Sparkle have a future saving people’s lives?</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation. Perfect for readers aged seven and up. Check out Jasmine’s other adventures: A Piglet Called Truffle, A Duckling Called Button, A Sheepdog Called Sky and many more!</p>",
    yearOfPublishing: 2021,
    genre: "Children's literature",
    numberOfPages: 144,
    coverType: "Hard cover",
  },
  {
    name: "A Foal Called Storm",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637360734/books/Foal-Storm_h4fbwh.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 220,
    publisher: "Noicy Crow",
    shortDescription: "Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself…",
    fullDescription: "<p>A perfect animal story for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon.</p><p>When Jasmine finds a lost foal in her father’s field, she can’t believe her eyes. Who would abandon such a beautiful creature, especially as it’s hurt its leg? With the race on to reunite Storm with his mother, Jasmine is determined to solve the mystery and bring the culprits to justice!</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation.</p>",
    yearOfPublishing: 2021,
    genre: "Children's literature",
    numberOfPages: 144,
    coverType: "Hard cover",
  },
  {
    name: "A Deer Called Dotty",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637360696/books/deer-Dotty_rqx2px.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 220,
    publisher: "Noicy Crow",
    shortDescription: "Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself…",
    fullDescription: "<p>A perfect animal story for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon.</p><p>Jasmine’s mother is called to help a pregnant deer who has been hit by a car. She performs an emergency Caesarean and delivers tiny, helpless Dotty, before handing her over to Jasmine to raise…</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation.</p>",
    yearOfPublishing: 2021,
    genre: "Children's literature",
    numberOfPages: 144,
    coverType: "Hard cover",
  },
  {
    name: "An Owl Called Star",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637360688/books/owl-Star_fdwhrc.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 220,
    publisher: "Noicy Crow",
    shortDescription: "The eighth in a fantastic series of animal stories for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon.",
    fullDescription: "<p>Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself…</p><p>When Jasmine and Tom discover an injured barn owl in the woods, they race to save his life. But as Star recovers, Jasmine realises that this beautiful bird is also a deadly hunter. Has Jasmine taken on more than she can handle?</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation. Perfect for readers aged seven and up.</p>",
    yearOfPublishing: 2019,
    genre: "Children's literature",
    numberOfPages: 144,
    coverType: "Hard cover",
  },
  {
    name: "A Donkey Called Mistletoe",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637360644/books/donkey-Mistletoe_qkiaxk.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 220,
    publisher: "Noicy Crow",
    shortDescription: "Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself…",
    fullDescription: "<p>A perfect animal story for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon</p><p>When Jasmine learns that Mr Hobson has grown too old to take care of his pet donkey, Mistletoe, she is determined that they won’t be parted. Of course, this means Mistletoe will have to come and live with her. With Christmas coming, how can she convince her parents to give her this most unusual present?</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation.</p>",
    yearOfPublishing: 2020,
    genre: "Children's literature",
    numberOfPages: 144,
    coverType: "Hard cover",
  },
  {
    name: "An Otter Called Pebble",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637361675/books/otter_euct0l.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 220,
    publisher: "Noicy Crow",
    shortDescription: "The seventh in a fantastic series of animal stories for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon.",
    fullDescription: "<p>Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself…</p><p>Jasmine and Tom are amazed to spot a baby otter alone on the riverbank. When the little cub is swept downstream, they risk everything to rescue her. But where is her family? Can Jasmine and Tom find Pebble’s home before it’s too late?</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation.</p>",
    yearOfPublishing: 2019,
    genre: "Children's literature",
    numberOfPages: 144,
    coverType: "Hard cover",
  },
  {
    name: "A Lamb Called Lucky",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637361666/books/lamb-Lucky_wsv1mp.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 220,
    publisher: "Noicy Crow",
    shortDescription: "The fifth in a fantastic series of animal stories for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon.",
    fullDescription: "<p>Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself…</p><p>It’s lambing time on the farm and Jasmine has her hands full. She has two orphaned baby birds to care for, as well as a tiny motherless lamb who needs her attention. She’s determined to look after little Lucky and keep him safe. But there are bigger dangers facing the flock, ones that come in the dead of night…</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation. Perfect for readers aged seven and up.</p>",
    yearOfPublishing: 2018,
    genre: "Children's literature",
    numberOfPages: 144,
    coverType: "Hard cover",
  },
  {
    name: "A Goat Called Willow",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637360606/books/goat-Willow_l2e4na.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 220,
    publisher: "Noicy Crow",
    shortDescription: "The sixth in a fantastic series of animal stories for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon.",
    fullDescription: "<p>Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself…</p><p>Jasmine has secretly rescued a baby goat. She’s gorgeous but she’s really naughty! Will her amazing antics persuade Jasmine’s parents to let her stay, or will Jasmine have to say goodbye to Willow for ever?</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation. Perfect for readers aged seven and up.</p>",
    yearOfPublishing: 2018,
    genre: "Children's literature",
    numberOfPages: 144,
    coverType: "Hard cover",
  },
];