const uniqueRandom = require("unique-random");
const rand = uniqueRandom(0, 999999);

module.exports = productsData = [
  {
    name: "A puppy called sparkle",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637360698/books/puppy-Sparkle_wu4rji.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 15,
    publisher: "Noicy Crow",
    shortDescription: "Jasmine falls in love at first sight with the little Golden Retriever puppy she rescues, but she knows she won't be able to keep Sparkle forever. Jasmine soon sees that the playful, friendly puppy is quick and eager to learn, and has an incredible sense of smell.",
    fullDescription: "<p>The twelfth in a fantastic series of animal stories for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon.</p><p>Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself… </p><p>Jasmine falls in love at first sight with the little Golden Retriever puppy she rescues, but she knows she won’t be able to keep Sparkle forever. Jasmine soon sees that the playful, friendly puppy is quick and eager to learn, and has an incredible sense of smell. When a new girl starts at Jasmine’s school, bringing her medical assistance dog with her, Jasmine starts to wonder. Could Sparkle have a future saving people’s lives?</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation. Perfect for readers aged seven and up. Check out Jasmine’s other adventures: A Piglet Called Truffle, A Duckling Called Button, A Sheepdog Called Sky and many more!</p>",
    yearOfPublishing: 2021,
    genre: "Children's literature",
    numberOfPages: 144,
    coverType: "Hard cover",
  },
  {
    name: "A Foal Called Storm",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637360734/books/Foal-Storm_h4fbwh.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 15,
    publisher: "Noicy Crow",
    shortDescription: "Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself…",
    fullDescription: "<p>A perfect animal story for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon.</p><p>When Jasmine finds a lost foal in her father’s field, she can’t believe her eyes. Who would abandon such a beautiful creature, especially as it’s hurt its leg? With the race on to reunite Storm with his mother, Jasmine is determined to solve the mystery and bring the culprits to justice!</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation.</p>",
    yearOfPublishing: 2021,
    genre: "Children's literature",
    numberOfPages: 144,
    coverType: "Hard cover",
  },
  {
    name: "A Deer Called Dotty",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637360696/books/deer-Dotty_rqx2px.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 15,
    publisher: "Noicy Crow",
    shortDescription: "Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself…",
    fullDescription: "<p>A perfect animal story for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon.</p><p>Jasmine’s mother is called to help a pregnant deer who has been hit by a car. She performs an emergency Caesarean and delivers tiny, helpless Dotty, before handing her over to Jasmine to raise…</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation.</p>",
    yearOfPublishing: 2021,
    genre: "Children's literature",
    numberOfPages: 144,
    coverType: "Hard cover",
  },
  {
    name: "An Owl Called Star",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637360688/books/owl-Star_fdwhrc.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 15,
    publisher: "Noicy Crow",
    shortDescription: "The eighth in a fantastic series of animal stories for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon.",
    fullDescription: "<p>Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself…</p><p>When Jasmine and Tom discover an injured barn owl in the woods, they race to save his life. But as Star recovers, Jasmine realises that this beautiful bird is also a deadly hunter. Has Jasmine taken on more than she can handle?</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation. Perfect for readers aged seven and up.</p>",
    yearOfPublishing: 2019,
    genre: "Children's literature",
    numberOfPages: 144,
    coverType: "Hard cover",
  },
  {
    name: "A Donkey Called Mistletoe",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637360644/books/donkey-Mistletoe_qkiaxk.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 15,
    publisher: "Noicy Crow",
    shortDescription: "Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself…",
    fullDescription: "<p>A perfect animal story for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon</p><p>When Jasmine learns that Mr Hobson has grown too old to take care of his pet donkey, Mistletoe, she is determined that they won’t be parted. Of course, this means Mistletoe will have to come and live with her. With Christmas coming, how can she convince her parents to give her this most unusual present?</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation.</p>",
    yearOfPublishing: 2020,
    genre: "Children's literature",
    numberOfPages: 144,
    coverType: "Hard cover",
  },
  {
    name: "An Otter Called Pebble",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637361675/books/otter_euct0l.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 15,
    publisher: "Noicy Crow",
    shortDescription: "The seventh in a fantastic series of animal stories for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon.",
    fullDescription: "<p>Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself…</p><p>Jasmine and Tom are amazed to spot a baby otter alone on the riverbank. When the little cub is swept downstream, they risk everything to rescue her. But where is her family? Can Jasmine and Tom find Pebble’s home before it’s too late?</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation.</p>",
    yearOfPublishing: 2019,
    genre: "Children's literature",
    numberOfPages: 144,
    coverType: "Hard cover",
  },
  {
    name: "A Lamb Called Lucky",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637361666/books/lamb-Lucky_wsv1mp.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 15,
    publisher: "Noicy Crow",
    shortDescription: "The fifth in a fantastic series of animal stories for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon.",
    fullDescription: "<p>Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself…</p><p>It’s lambing time on the farm and Jasmine has her hands full. She has two orphaned baby birds to care for, as well as a tiny motherless lamb who needs her attention. She’s determined to look after little Lucky and keep him safe. But there are bigger dangers facing the flock, ones that come in the dead of night…</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation. Perfect for readers aged seven and up.</p>",
    yearOfPublishing: 2018,
    genre: "Children's literature",
    numberOfPages: 144,
    coverType: "Hard cover",
  },
  {
    name: "A Goat Called Willow",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637360606/books/goat-Willow_l2e4na.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 15,
    publisher: "Noicy Crow",
    shortDescription: "The sixth in a fantastic series of animal stories for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon.",
    fullDescription: "<p>Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself…</p><p>Jasmine has secretly rescued a baby goat. She’s gorgeous but she’s really naughty! Will her amazing antics persuade Jasmine’s parents to let her stay, or will Jasmine have to say goodbye to Willow for ever?</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation. Perfect for readers aged seven and up.</p>",
    yearOfPublishing: 2018,
    genre: "Children's literature",
    numberOfPages: 144,
    coverType: "Hard cover",
  },
  {
    name: "Fledgling",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637421190/books/Fledgling_jp3jcz.jpg"],
    quantity: 30,
    author: "6198cbc8d584625da10c9ee5",
    categories: "paper-books",
    currentPrice: 15,
    publisher: "Noicy Crow",
    shortDescription: "A dark, gothic adventure set deep in a Bavarian forest, with angels and owls and magic and a boy who isn't all that he seems to be...  A cherub is blown into Cassie Engel's bedroom during a thunderstorm, triggering a series of terrifying events. Cassie must discover if its arrival was an accident or part of something more sinister. ",
    fullDescription: "<p>A dark, gothic adventure set deep in a Bavarian forest, with angels and owls and magic and a boy who isn’t all that he seems to be…</p><p>A cherub is blown into Cassie Engel’s bedroom during a thunderstorm, triggering a series of terrifying events. Cassie must discover if its arrival was an accident or part of something more sinister.</p><p>With a self-obsessed opera singer for a mother, a strange taxidermist father, and a best friend who isn’t quite what he seems, Cassie is forced to unearth the secrets of her family’s past. As the dark forces gather around them, can Cassie protect all that she holds dear?</p><p>The fantastic debut novel from Lucy Hope, with cover illustration by Anna Shepeta.</p>",
    yearOfPublishing: 2021,
    genre: "Children's literature",
    numberOfPages: 288,
    coverType: "Soft cover",
  },
  {
    name: "Fledgling",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637421190/books/Fledgling_jp3jcz.jpg"],
    quantity: 30,
    author: "6198cbc8d584625da10c9ee5",
    categories: "audio-books",
    currentPrice: 5,
    publisher: "Noicy Crow",
    shortDescription: "A dark, gothic adventure set deep in a Bavarian forest, with angels and owls and magic and a boy who isn't all that he seems to be...  A cherub is blown into Cassie Engel's bedroom during a thunderstorm, triggering a series of terrifying events. Cassie must discover if its arrival was an accident or part of something more sinister. ",
    fullDescription: "<p>A dark, gothic adventure set deep in a Bavarian forest, with angels and owls and magic and a boy who isn’t all that he seems to be…</p><p>A cherub is blown into Cassie Engel’s bedroom during a thunderstorm, triggering a series of terrifying events. Cassie must discover if its arrival was an accident or part of something more sinister.</p><p>With a self-obsessed opera singer for a mother, a strange taxidermist father, and a best friend who isn’t quite what he seems, Cassie is forced to unearth the secrets of her family’s past. As the dark forces gather around them, can Cassie protect all that she holds dear?</p><p>The fantastic debut novel from Lucy Hope, with cover illustration by Anna Shepeta.</p>",
    yearOfPublishing: 2021,
    duration: 8,
    genre: "Children's literature"
  },
  {
    name: "In a Holidaze",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637421185/books/9781982123949-l_qftkqp.jpg"],
    quantity: 30,
    author: "619917e7fdd16e771992e734",
    categories: "ebooks",
    currentPrice: 5,
    publisher: "Gallery Books",
    shortDescription: "It’s the most wonderful time of the year…but not for Maelyn Jones. She’s living with her parents, hates her going-nowhere job, and has just made a romantic error of epic proportions. But perhaps worst of all, this is the last Christmas Mae will be at her favorite place in the world—the snowy Utah cabin where she and her family have spent every holiday since she was born, along with two other beloved families. ",
    fullDescription: "<p>It’s the most wonderful time of the year…but not for Maelyn Jones. She’s living with her parents, hates her going-nowhere job, and has just made a romantic error of epic proportions.</p><p>But perhaps worst of all, this is the last Christmas Mae will be at her favorite place in the world—the snowy Utah cabin where she and her family have spent every holiday since she was born, along with two other beloved families. Mentally melting down as she drives away from the cabin for the final time, Mae throws out what she thinks is a simple plea to the universe: Please. Show me what will make me happy.</p><p>The next thing she knows, tires screech and metal collides, everything goes black. But when Mae gasps awake…she’s on an airplane bound for Utah, where she begins the same holiday all over again. With one hilarious disaster after another sending her back to the plane, Mae must figure out how to break free of the strange time loop—and finally get her true love under the mistletoe.</p><p>Jam-packed with yuletide cheer, an unforgettable cast of characters, and Christina Lauren’s trademark “downright hilarious” (Helen Hoang, author of The Bride Test) hijinks, this swoon-worthy romantic read will make you believe in the power of wishes and the magic of the holidays.</p>",
    yearOfPublishing: 2020,
    genre: "Fiction",
    numberOfPages: 307
  },
  {
    name: "In a Holidaze",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637421185/books/9781982123949-l_qftkqp.jpg"],
    quantity: 30,
    author: "619917e7fdd16e771992e734",
    categories: "audio-books",
    currentPrice: 5,
    publisher: "Gallery Books",
    shortDescription: "It’s the most wonderful time of the year…but not for Maelyn Jones. She’s living with her parents, hates her going-nowhere job, and has just made a romantic error of epic proportions. But perhaps worst of all, this is the last Christmas Mae will be at her favorite place in the world—the snowy Utah cabin where she and her family have spent every holiday since she was born, along with two other beloved families. ",
    fullDescription: "<p>It’s the most wonderful time of the year…but not for Maelyn Jones. She’s living with her parents, hates her going-nowhere job, and has just made a romantic error of epic proportions.</p><p>But perhaps worst of all, this is the last Christmas Mae will be at her favorite place in the world—the snowy Utah cabin where she and her family have spent every holiday since she was born, along with two other beloved families. Mentally melting down as she drives away from the cabin for the final time, Mae throws out what she thinks is a simple plea to the universe: Please. Show me what will make me happy.</p><p>The next thing she knows, tires screech and metal collides, everything goes black. But when Mae gasps awake…she’s on an airplane bound for Utah, where she begins the same holiday all over again. With one hilarious disaster after another sending her back to the plane, Mae must figure out how to break free of the strange time loop—and finally get her true love under the mistletoe.</p><p>Jam-packed with yuletide cheer, an unforgettable cast of characters, and Christina Lauren’s trademark “downright hilarious” (Helen Hoang, author of The Bride Test) hijinks, this swoon-worthy romantic read will make you believe in the power of wishes and the magic of the holidays.</p>",
    yearOfPublishing: 2020,
    genre: "Fiction",
    duration: 12
  },
  {
    name: "In a Holidaze",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637421185/books/9781982123949-l_qftkqp.jpg"],
    quantity: 30,
    author: "619917e7fdd16e771992e734",
    categories: "paper-books",
    currentPrice: 10,
    publisher: "Gallery Books",
    shortDescription: "It’s the most wonderful time of the year…but not for Maelyn Jones. She’s living with her parents, hates her going-nowhere job, and has just made a romantic error of epic proportions. But perhaps worst of all, this is the last Christmas Mae will be at her favorite place in the world—the snowy Utah cabin where she and her family have spent every holiday since she was born, along with two other beloved families. ",
    fullDescription: "<p>It’s the most wonderful time of the year…but not for Maelyn Jones. She’s living with her parents, hates her going-nowhere job, and has just made a romantic error of epic proportions.</p><p>But perhaps worst of all, this is the last Christmas Mae will be at her favorite place in the world—the snowy Utah cabin where she and her family have spent every holiday since she was born, along with two other beloved families. Mentally melting down as she drives away from the cabin for the final time, Mae throws out what she thinks is a simple plea to the universe: Please. Show me what will make me happy.</p><p>The next thing she knows, tires screech and metal collides, everything goes black. But when Mae gasps awake…she’s on an airplane bound for Utah, where she begins the same holiday all over again. With one hilarious disaster after another sending her back to the plane, Mae must figure out how to break free of the strange time loop—and finally get her true love under the mistletoe.</p><p>Jam-packed with yuletide cheer, an unforgettable cast of characters, and Christina Lauren’s trademark “downright hilarious” (Helen Hoang, author of The Bride Test) hijinks, this swoon-worthy romantic read will make you believe in the power of wishes and the magic of the holidays.</p>",
    yearOfPublishing: 2020,
    genre: "Fiction",
    numberOfPages: 307,
    coverType: "Soft cover",
  },
  {
    name: "The Honey-Don't List",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637433702/books/9781982123918-l_xxz1yd.jpg"],
    quantity: 150,
    author: "619917e7fdd16e771992e734",
    categories: "audio-books",
    currentPrice: 5,
    publisher: "Gallery Books",
    shortDescription: "Carey Duncan has worked for home remodeling and design gurus Melissa and Rusty Tripp for nearly a decade. A country girl at heart, Carey started in their first store at sixteen, and - more than anyone would suspect - has helped them build an empire. With a new show and a book about to launch, the Tripps are on the verge of superstardom. There’s only one problem: America’s favorite couple can’t stand each other.",
    fullDescription: "<p>Carey Duncan has worked for home remodeling and design gurus Melissa and Rusty Tripp for nearly a decade. A country girl at heart, Carey started in their first store at sixteen, and - more than anyone would suspect - has helped them build an empire. With a new show and a book about to launch, the Tripps are on the verge of superstardom. There’s only one problem: America’s favorite couple can’t stand each other.</p><p>James McCann, MIT graduate and engineering genius, was originally hired as a structural engineer, but the job isn’t all he thought it’d be. The last straw? Both he and Carey must go on book tour with the Tripps and keep the wheels from falling off the proverbial bus.</p><p>Unfortunately, neither of them is in any position to quit. Carey needs health insurance, and James has been promised the role of a lifetime if he can just keep the couple on track for a few more weeks. While road-tripping with the Tripps up the West Coast, Carey and James vow to work together to keep their bosses’ secrets hidden, and their own jobs secure. But if they stop playing along - and start playing for keeps - they may have the chance to build something beautiful together…</p>",
    yearOfPublishing: 2020,
    genre: "Fiction",
    duration: 13,
    coverType: "Hard cover",
  },
  {
    name: "The Honey-Don't List",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637433702/books/9781982123918-l_xxz1yd.jpg"],
    quantity: 50,
    author: "619917e7fdd16e771992e734",
    categories: "paper-books",
    currentPrice: 10,
    publisher: "Gallery Books",
    shortDescription: "Carey Duncan has worked for home remodeling and design gurus Melissa and Rusty Tripp for nearly a decade. A country girl at heart, Carey started in their first store at sixteen, and - more than anyone would suspect - has helped them build an empire. With a new show and a book about to launch, the Tripps are on the verge of superstardom. There’s only one problem: America’s favorite couple can’t stand each other.",
    fullDescription: "<p>Carey Duncan has worked for home remodeling and design gurus Melissa and Rusty Tripp for nearly a decade. A country girl at heart, Carey started in their first store at sixteen, and - more than anyone would suspect - has helped them build an empire. With a new show and a book about to launch, the Tripps are on the verge of superstardom. There’s only one problem: America’s favorite couple can’t stand each other.</p><p>James McCann, MIT graduate and engineering genius, was originally hired as a structural engineer, but the job isn’t all he thought it’d be. The last straw? Both he and Carey must go on book tour with the Tripps and keep the wheels from falling off the proverbial bus.</p><p>Unfortunately, neither of them is in any position to quit. Carey needs health insurance, and James has been promised the role of a lifetime if he can just keep the couple on track for a few more weeks. While road-tripping with the Tripps up the West Coast, Carey and James vow to work together to keep their bosses’ secrets hidden, and their own jobs secure. But if they stop playing along - and start playing for keeps - they may have the chance to build something beautiful together…</p>",
    yearOfPublishing: 2020,
    genre: "Fiction",
    numberOfPages: 308,
    coverType: "Hard cover",
  },
  {
    name: "The Honey-Don't List",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637433702/books/9781982123918-l_xxz1yd.jpg"],
    quantity: 50,
    author: "619917e7fdd16e771992e734",
    categories: "paper-books",
    currentPrice: 10,
    publisher: "Gallery Books",
    shortDescription: "Carey Duncan has worked for home remodeling and design gurus Melissa and Rusty Tripp for nearly a decade. A country girl at heart, Carey started in their first store at sixteen, and - more than anyone would suspect - has helped them build an empire. With a new show and a book about to launch, the Tripps are on the verge of superstardom. There’s only one problem: America’s favorite couple can’t stand each other.",
    fullDescription: "<p>Carey Duncan has worked for home remodeling and design gurus Melissa and Rusty Tripp for nearly a decade. A country girl at heart, Carey started in their first store at sixteen, and - more than anyone would suspect - has helped them build an empire. With a new show and a book about to launch, the Tripps are on the verge of superstardom. There’s only one problem: America’s favorite couple can’t stand each other.</p><p>James McCann, MIT graduate and engineering genius, was originally hired as a structural engineer, but the job isn’t all he thought it’d be. The last straw? Both he and Carey must go on book tour with the Tripps and keep the wheels from falling off the proverbial bus.</p><p>Unfortunately, neither of them is in any position to quit. Carey needs health insurance, and James has been promised the role of a lifetime if he can just keep the couple on track for a few more weeks. While road-tripping with the Tripps up the West Coast, Carey and James vow to work together to keep their bosses’ secrets hidden, and their own jobs secure. But if they stop playing along - and start playing for keeps - they may have the chance to build something beautiful together…</p>",
    yearOfPublishing: 2020,
    genre: "Fiction",
    numberOfPages: 308,
    coverType: "Hard cover",
  },
  {
    name: "How to Make the World Add Up: Ten Rules for Thinking Differently About Numbers",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637436733/books/9780349143866_llwrby.jpg"],
    quantity: 50,
    author: "61994c39cdfe2d8b4aa92547",
    categories: "paper-books",
    currentPrice: 10,
    publisher: "Brown",
    shortDescription: "If you aren't in love with stats before reading this book, you will be by the time you're done. Powerful, persuasive, and in these truth-defying times, indispensable'Caroline Criado Perez, author of Invisible Women'Nobody makes the statistics of everyday life more fascinating and enjoyable than Tim Harford'Bill Bryson'Fabulously readable, lucid, witty and authoritative",
    fullDescription: "<p>If you aren't in love with stats before reading this book, you will be by the time you're done. Powerful, persuasive, and in these truth-defying times, indispensable'Caroline Criado Perez, author of Invisible Women'Nobody makes the statistics of everyday life more fascinating and enjoyable than Tim Harford'Bill Bryson'Fabulously readable, lucid, witty and authoritative</p><p>Every politician and journalist should be made to read this book, but everyone else will get so much pleasure and draw so much strength from the joyful way it dispels the clouds of deceit and delusion' Stephen Fry'Wise, humane and, above all, illuminating. Nobody is better on statistics and numbers - and how to make sense of them'Matthew SyedWhen was the last time you read a grand statement, accompanied by a large number, and wondered whether it could really be true Statistics are vital in helping us tell stories - we see them in the papers, on social media, and we hear them used in everyday conversation - and yet we doubt them more than ever. But numbers - in the right hands - have the power to change the world for the better.</p><p>Contrary to popular belief, good statistics are not a trick, although they are a kind of magic. Good statistics are not smoke and mirrors; in fact, they help us see more clearly. Good statistics are like a telescope for an astronomer, a microscope for a bacteriologist, or an X-ray for a radiologist. If we are willing to let them, good statistics help us see things about the world around us and about ourselves - both large and small - that we would not be able to see in any other way.</p><p>In How to Make the World Add Up, Tim Harford draws on his experience as both an economist and presenter of the BBC's radio show 'More or Less'. He takes us deep into the world of disinformation and obfuscation, bad research and misplaced motivation to find those priceless jewels of data and analysis that make communicating with numbers worthwhile</p>",
    yearOfPublishing: 2020,
    genre: "Business literature",
    numberOfPages: 304,
    coverType: "Hard cover",
  },
  {
    name: "How to Make the World Add Up: Ten Rules for Thinking Differently About Numbers",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637436733/books/9780349143866_llwrby.jpg"],
    quantity: 100,
    author: "61994c39cdfe2d8b4aa92547",
    categories: "ebooks",
    currentPrice: 10,
    publisher: "Brown",
    shortDescription: "If you aren't in love with stats before reading this book, you will be by the time you're done. Powerful, persuasive, and in these truth-defying times, indispensable'Caroline Criado Perez, author of Invisible Women'Nobody makes the statistics of everyday life more fascinating and enjoyable than Tim Harford'Bill Bryson'Fabulously readable, lucid, witty and authoritative",
    fullDescription: "<p>If you aren't in love with stats before reading this book, you will be by the time you're done. Powerful, persuasive, and in these truth-defying times, indispensable'Caroline Criado Perez, author of Invisible Women'Nobody makes the statistics of everyday life more fascinating and enjoyable than Tim Harford'Bill Bryson'Fabulously readable, lucid, witty and authoritative</p><p>Every politician and journalist should be made to read this book, but everyone else will get so much pleasure and draw so much strength from the joyful way it dispels the clouds of deceit and delusion' Stephen Fry'Wise, humane and, above all, illuminating. Nobody is better on statistics and numbers - and how to make sense of them'Matthew SyedWhen was the last time you read a grand statement, accompanied by a large number, and wondered whether it could really be true Statistics are vital in helping us tell stories - we see them in the papers, on social media, and we hear them used in everyday conversation - and yet we doubt them more than ever. But numbers - in the right hands - have the power to change the world for the better.</p><p>Contrary to popular belief, good statistics are not a trick, although they are a kind of magic. Good statistics are not smoke and mirrors; in fact, they help us see more clearly. Good statistics are like a telescope for an astronomer, a microscope for a bacteriologist, or an X-ray for a radiologist. If we are willing to let them, good statistics help us see things about the world around us and about ourselves - both large and small - that we would not be able to see in any other way.</p><p>In How to Make the World Add Up, Tim Harford draws on his experience as both an economist and presenter of the BBC's radio show 'More or Less'. He takes us deep into the world of disinformation and obfuscation, bad research and misplaced motivation to find those priceless jewels of data and analysis that make communicating with numbers worthwhile</p>",
    yearOfPublishing: 2020,
    genre: "Business literature",
    numberOfPages: 304
  },
  {
    name: "How to Make the World Add Up: Ten Rules for Thinking Differently About Numbers",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637436733/books/9780349143866_llwrby.jpg"],
    quantity: 100,
    author: "61994c39cdfe2d8b4aa92547",
    categories: "audio-books",
    currentPrice: 15,
    publisher: "Brown",
    shortDescription: "If you aren't in love with stats before reading this book, you will be by the time you're done. Powerful, persuasive, and in these truth-defying times, indispensable'Caroline Criado Perez, author of Invisible Women'Nobody makes the statistics of everyday life more fascinating and enjoyable than Tim Harford'Bill Bryson'Fabulously readable, lucid, witty and authoritative",
    fullDescription: "<p>If you aren't in love with stats before reading this book, you will be by the time you're done. Powerful, persuasive, and in these truth-defying times, indispensable'Caroline Criado Perez, author of Invisible Women'Nobody makes the statistics of everyday life more fascinating and enjoyable than Tim Harford'Bill Bryson'Fabulously readable, lucid, witty and authoritative</p><p>Every politician and journalist should be made to read this book, but everyone else will get so much pleasure and draw so much strength from the joyful way it dispels the clouds of deceit and delusion' Stephen Fry'Wise, humane and, above all, illuminating. Nobody is better on statistics and numbers - and how to make sense of them'Matthew SyedWhen was the last time you read a grand statement, accompanied by a large number, and wondered whether it could really be true Statistics are vital in helping us tell stories - we see them in the papers, on social media, and we hear them used in everyday conversation - and yet we doubt them more than ever. But numbers - in the right hands - have the power to change the world for the better.</p><p>Contrary to popular belief, good statistics are not a trick, although they are a kind of magic. Good statistics are not smoke and mirrors; in fact, they help us see more clearly. Good statistics are like a telescope for an astronomer, a microscope for a bacteriologist, or an X-ray for a radiologist. If we are willing to let them, good statistics help us see things about the world around us and about ourselves - both large and small - that we would not be able to see in any other way.</p><p>In How to Make the World Add Up, Tim Harford draws on his experience as both an economist and presenter of the BBC's radio show 'More or Less'. He takes us deep into the world of disinformation and obfuscation, bad research and misplaced motivation to find those priceless jewels of data and analysis that make communicating with numbers worthwhile</p>",
    yearOfPublishing: 2020,
    genre: "Business literature",
    duration: 45
  },
  {
    name: "The Next Fifty Things that Made the Modern Economy",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637438116/books/9780349144030_rxldtg.jpg"],
    quantity: 100,
    author: "61994c39cdfe2d8b4aa92547",
    categories: "audio-books",
    currentPrice: 5,
    publisher: "Brown",
    shortDescription: "Following on from the brilliant Fifty Things That Made the Modern Economy, the bestselling economist Tim Harford explores another fifty items – from bricks to postage stamps – that have played a key role in shaping our global story.",
    fullDescription: "<p>In Fifty Things that Made the Modern Economy, the revolutionary, acclaimed book, radio series and podcast, bestselling economist Tim Harford introduced us to a selection of fifty radical inventions that changed the world.</p><p>Now, in this new book, Harford once again brings us an array of remarkable, memorable, curious and often unexpected 'things' - inventions that teach us lessons by turns intimate and sweeping about the complex world economy we live in today.</p><p>From the brick, blockchain and the bicycle to fire, the factory and fundraising, and from solar PV and the pencil to the postage stamp, this brilliant and enlightening collection resonates, fascinates and stimulates. It is a wonderful blend of insight and inspiration from one of Britain's finest non-fiction storytellers.</p>",
    yearOfPublishing: 2021,
    genre: "Business literature",
    duration: 65
  },
  {
    name: "The Next Fifty Things that Made the Modern Economy",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637438116/books/9780349144030_rxldtg.jpg"],
    quantity: 100,
    author: "61994c39cdfe2d8b4aa92547",
    categories: "ebooks",
    currentPrice: 5,
    publisher: "Brown",
    shortDescription: "Following on from the brilliant Fifty Things That Made the Modern Economy, the bestselling economist Tim Harford explores another fifty items – from bricks to postage stamps – that have played a key role in shaping our global story.",
    fullDescription: "<p>In Fifty Things that Made the Modern Economy, the revolutionary, acclaimed book, radio series and podcast, bestselling economist Tim Harford introduced us to a selection of fifty radical inventions that changed the world.</p><p>Now, in this new book, Harford once again brings us an array of remarkable, memorable, curious and often unexpected 'things' - inventions that teach us lessons by turns intimate and sweeping about the complex world economy we live in today.</p><p>From the brick, blockchain and the bicycle to fire, the factory and fundraising, and from solar PV and the pencil to the postage stamp, this brilliant and enlightening collection resonates, fascinates and stimulates. It is a wonderful blend of insight and inspiration from one of Britain's finest non-fiction storytellers.</p>",
    yearOfPublishing: 2021,
    genre: "Business literature",
    numberOfPages: 352
  },
  {
    name: "The Next Fifty Things that Made the Modern Economy",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637438116/books/9780349144030_rxldtg.jpg"],
    quantity: 100,
    author: "61994c39cdfe2d8b4aa92547",
    categories: "paper-books",
    currentPrice: 15,
    publisher: "Brown",
    shortDescription: "Following on from the brilliant Fifty Things That Made the Modern Economy, the bestselling economist Tim Harford explores another fifty items – from bricks to postage stamps – that have played a key role in shaping our global story.",
    fullDescription: "<p>In Fifty Things that Made the Modern Economy, the revolutionary, acclaimed book, radio series and podcast, bestselling economist Tim Harford introduced us to a selection of fifty radical inventions that changed the world.</p><p>Now, in this new book, Harford once again brings us an array of remarkable, memorable, curious and often unexpected 'things' - inventions that teach us lessons by turns intimate and sweeping about the complex world economy we live in today.</p><p>From the brick, blockchain and the bicycle to fire, the factory and fundraising, and from solar PV and the pencil to the postage stamp, this brilliant and enlightening collection resonates, fascinates and stimulates. It is a wonderful blend of insight and inspiration from one of Britain's finest non-fiction storytellers.</p>",
    yearOfPublishing: 2021,
    genre: "Business literature",
    numberOfPages: 352,
    coverType: "Hard cover",
  },
  {
    name: "The Data Detective: Ten Easy Rules to Make Sense of Statistics",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637438819/books/41GD6oSy8PL_wbrrfa.jpg"],
    quantity: 300,
    author: "61994c39cdfe2d8b4aa92547",
    categories: "paper-books",
    currentPrice: 10,
    publisher: "Riverhead Books",
    shortDescription: "Today we think statistics are the enemy, numbers used to mislead and confuse us. That’s a mistake, Tim Harford says in The Data Detective. We shouldn’t be suspicious of statistics—we need to understand what they mean and how they can improve our lives: they are, at heart, human behavior seen through the prism of numbers and are often “the only way of grasping much of what is going on around us.",
    fullDescription: "<p>Today we think statistics are the enemy, numbers used to mislead and confuse us. That’s a mistake, Tim Harford says in The Data Detective. We shouldn’t be suspicious of statistics—we need to understand what they mean and how they can improve our lives: they are, at heart, human behavior seen through the prism of numbers and are often “the only way of grasping much of what is going on around us.</p><p>If we can toss aside our fears and learn to approach them clearly—understanding how our own preconceptions lead us astray—statistics can point to ways we can live better and work smarter.</p><p>As “perhaps the best popular economics writer in the world” (New Statesman), Tim Harford is an expert at taking complicated ideas and untangling them for millions of readers. In The Data Detective, he uses new research in science and psychology to set out ten strategies for using statistics to erase our biases and replace them with new ideas that use virtues like patience, curiosity, and good sense to better understand ourselves and the world.</p><p>As a result, The Data Detective is a big-idea book about statistics and human behavior that is fresh, unexpected, and insightful.</p>",
    yearOfPublishing: 2021,
    genre: "Business literature",
    numberOfPages: 334,
    coverType: "Soft cover",
  },
  {
    name: "The Data Detective: Ten Easy Rules to Make Sense of Statistics",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637438819/books/41GD6oSy8PL_wbrrfa.jpg"],
    quantity: 300,
    author: "61994c39cdfe2d8b4aa92547",
    categories: "ebooks",
    currentPrice: 5,
    publisher: "Riverhead Books",
    shortDescription: "Today we think statistics are the enemy, numbers used to mislead and confuse us. That’s a mistake, Tim Harford says in The Data Detective. We shouldn’t be suspicious of statistics—we need to understand what they mean and how they can improve our lives: they are, at heart, human behavior seen through the prism of numbers and are often “the only way of grasping much of what is going on around us.",
    fullDescription: "<p>Today we think statistics are the enemy, numbers used to mislead and confuse us. That’s a mistake, Tim Harford says in The Data Detective. We shouldn’t be suspicious of statistics—we need to understand what they mean and how they can improve our lives: they are, at heart, human behavior seen through the prism of numbers and are often “the only way of grasping much of what is going on around us.</p><p>If we can toss aside our fears and learn to approach them clearly—understanding how our own preconceptions lead us astray—statistics can point to ways we can live better and work smarter.</p><p>As “perhaps the best popular economics writer in the world” (New Statesman), Tim Harford is an expert at taking complicated ideas and untangling them for millions of readers. In The Data Detective, he uses new research in science and psychology to set out ten strategies for using statistics to erase our biases and replace them with new ideas that use virtues like patience, curiosity, and good sense to better understand ourselves and the world.</p><p>As a result, The Data Detective is a big-idea book about statistics and human behavior that is fresh, unexpected, and insightful.</p>",
    yearOfPublishing: 2021,
    genre: "Business literature",
    numberOfPages: 334
  },
];