const uniqueRandom = require("unique-random");
const rand = uniqueRandom(0, 999999);

module.exports = productsData = [
  {
    name: "A puppy called sparkle",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637360698/books/puppy-Sparkle_wu4rji.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    previousPrice: 25,
    currentPrice: 15,
    publisher: "noicy-crow",
    shortDescription: "Jasmine falls in love at first sight with the little Golden Retriever puppy she rescues, but she knows she won't be able to keep Sparkle forever. Jasmine soon sees that the playful, friendly puppy is quick and eager to learn, and has an incredible sense of smell.",
    fullDescription: "<p>The twelfth in a fantastic series of animal stories for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon.</p><p>Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself… </p><p>Jasmine falls in love at first sight with the little Golden Retriever puppy she rescues, but she knows she won’t be able to keep Sparkle forever. Jasmine soon sees that the playful, friendly puppy is quick and eager to learn, and has an incredible sense of smell. When a new girl starts at Jasmine’s school, bringing her medical assistance dog with her, Jasmine starts to wonder. Could Sparkle have a future saving people’s lives?</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation. Perfect for readers aged seven and up. Check out Jasmine’s other adventures: A Piglet Called Truffle, A Duckling Called Button, A Sheepdog Called Sky and many more!</p>",
    yearOfPublishing: new Date("2021"),
    genre: "children-literature",
    numberOfPages: 144,
    coverType: "hard",
  },
  {
    name: "A Foal Called Storm",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637360734/books/Foal-Storm_h4fbwh.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 15,
    previousPrice: 20,
    publisher: "noicy-crow",
    shortDescription: "Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself…",
    fullDescription: "<p>A perfect animal story for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon.</p><p>When Jasmine finds a lost foal in her father’s field, she can’t believe her eyes. Who would abandon such a beautiful creature, especially as it’s hurt its leg? With the race on to reunite Storm with his mother, Jasmine is determined to solve the mystery and bring the culprits to justice!</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation.</p>",
    yearOfPublishing: new Date("2021"),
    genre: "children-literature",
    numberOfPages: 144,
    coverType: "hard",
  },
  {
    name: "A Deer Called Dotty",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637360696/books/deer-Dotty_rqx2px.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 15,
    publisher: "noicy-crow",
    shortDescription: "Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself…",
    fullDescription: "<p>A perfect animal story for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon.</p><p>Jasmine’s mother is called to help a pregnant deer who has been hit by a car. She performs an emergency Caesarean and delivers tiny, helpless Dotty, before handing her over to Jasmine to raise…</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation.</p>",
    yearOfPublishing: new Date("2021"),
    genre: "children-literature",
    numberOfPages: 144,
    coverType: "hard",
  },
  {
    name: "An Owl Called Star",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637360688/books/owl-Star_fdwhrc.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 15,
    previousPrice: 20,
    publisher: "noicy-crow",
    shortDescription: "The eighth in a fantastic series of animal stories for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon.",
    fullDescription: "<p>Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself…</p><p>When Jasmine and Tom discover an injured barn owl in the woods, they race to save his life. But as Star recovers, Jasmine realises that this beautiful bird is also a deadly hunter. Has Jasmine taken on more than she can handle?</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation. Perfect for readers aged seven and up.</p>",
    yearOfPublishing: new Date("2019"),
    genre: "children-literature",
    numberOfPages: 144,
    coverType: "hard",
  },
  {
    name: "A Donkey Called Mistletoe",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637360644/books/donkey-Mistletoe_qkiaxk.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 15,
    previousPrice: 25,
    publisher: "noicy-crow",
    shortDescription: "Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself…",
    fullDescription: "<p>A perfect animal story for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon</p><p>When Jasmine learns that Mr Hobson has grown too old to take care of his pet donkey, Mistletoe, she is determined that they won’t be parted. Of course, this means Mistletoe will have to come and live with her. With Christmas coming, how can she convince her parents to give her this most unusual present?</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation.</p>",
    yearOfPublishing: new Date("2020"),
    genre: "children-literature",
    numberOfPages: 144,
    coverType: "hard",
  },
  {
    name: "An Otter Called Pebble",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637361675/books/otter_euct0l.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 15,
    publisher: "noicy-crow",
    shortDescription: "The seventh in a fantastic series of animal stories for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon.",
    fullDescription: "<p>Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself…</p><p>Jasmine and Tom are amazed to spot a baby otter alone on the riverbank. When the little cub is swept downstream, they risk everything to rescue her. But where is her family? Can Jasmine and Tom find Pebble’s home before it’s too late?</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation.</p>",
    yearOfPublishing: new Date("2019"),
    genre: "children-literature",
    numberOfPages: 144,
    coverType: "hard",
  },
  {
    name: "A Lamb Called Lucky",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637361666/books/lamb-Lucky_wsv1mp.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 15,
    publisher: "noicy-crow",
    shortDescription: "The fifth in a fantastic series of animal stories for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon.",
    fullDescription: "<p>Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself…</p><p>It’s lambing time on the farm and Jasmine has her hands full. She has two orphaned baby birds to care for, as well as a tiny motherless lamb who needs her attention. She’s determined to look after little Lucky and keep him safe. But there are bigger dangers facing the flock, ones that come in the dead of night…</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation. Perfect for readers aged seven and up.</p>",
    yearOfPublishing: new Date("2018"),
    genre: "children-literature",
    numberOfPages: 144,
    coverType: "hard",
  },
  {
    name: "A Goat Called Willow",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637360606/books/goat-Willow_l2e4na.jpg"],
    quantity: 10,
    author: "619670e222fce45aa6a6dd27",
    categories: "paper-books",
    currentPrice: 15,
    publisher: "noicy-crow",
    shortDescription: "The sixth in a fantastic series of animal stories for younger readers by Waterstones Children’s Book Prize-shortlisted author Helen Peters, with beautiful black-and-white illustrations by Ellie Snowdon.",
    fullDescription: "<p>Jasmine’s dad is a farmer, and her mum is a large-animal vet, so Jasmine spends a lot of time caring for animals and keeping them out of trouble. Unfortunately, this often means she gets into hot water herself…</p><p>Jasmine has secretly rescued a baby goat. She’s gorgeous but she’s really naughty! Will her amazing antics persuade Jasmine’s parents to let her stay, or will Jasmine have to say goodbye to Willow for ever?</p><p>Brilliant storytelling that will make you laugh and cry, this is Dick King-Smith for a new generation. Perfect for readers aged seven and up.</p>",
    yearOfPublishing: new Date("2018"),
    genre: "children-literature",
    numberOfPages: 144,
    coverType: "hard",
  },
  {
    name: "Fledgling",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637421190/books/Fledgling_jp3jcz.jpg"],
    quantity: 30,
    author: "6198cbc8d584625da10c9ee5",
    categories: "paper-books",
    currentPrice: 15,
    publisher: "noicy-crow",
    shortDescription: "A dark, gothic adventure set deep in a Bavarian forest, with angels and owls and magic and a boy who isn't all that he seems to be...  A cherub is blown into Cassie Engel's bedroom during a thunderstorm, triggering a series of terrifying events. Cassie must discover if its arrival was an accident or part of something more sinister. ",
    fullDescription: "<p>A dark, gothic adventure set deep in a Bavarian forest, with angels and owls and magic and a boy who isn’t all that he seems to be…</p><p>A cherub is blown into Cassie Engel’s bedroom during a thunderstorm, triggering a series of terrifying events. Cassie must discover if its arrival was an accident or part of something more sinister.</p><p>With a self-obsessed opera singer for a mother, a strange taxidermist father, and a best friend who isn’t quite what he seems, Cassie is forced to unearth the secrets of her family’s past. As the dark forces gather around them, can Cassie protect all that she holds dear?</p><p>The fantastic debut novel from Lucy Hope, with cover illustration by Anna Shepeta.</p>",
    yearOfPublishing: new Date("2021"),
    genre: "children-literature",
    numberOfPages: 288,
    coverType: "soft",
  },
  {
    name: "Fledgling",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637421190/books/Fledgling_jp3jcz.jpg"],
    quantity: 30,
    author: "6198cbc8d584625da10c9ee5",
    categories: "audio-books",
    currentPrice: 5,
    publisher: "noicy-crow",
    shortDescription: "A dark, gothic adventure set deep in a Bavarian forest, with angels and owls and magic and a boy who isn't all that he seems to be...  A cherub is blown into Cassie Engel's bedroom during a thunderstorm, triggering a series of terrifying events. Cassie must discover if its arrival was an accident or part of something more sinister. ",
    fullDescription: "<p>A dark, gothic adventure set deep in a Bavarian forest, with angels and owls and magic and a boy who isn’t all that he seems to be…</p><p>A cherub is blown into Cassie Engel’s bedroom during a thunderstorm, triggering a series of terrifying events. Cassie must discover if its arrival was an accident or part of something more sinister.</p><p>With a self-obsessed opera singer for a mother, a strange taxidermist father, and a best friend who isn’t quite what he seems, Cassie is forced to unearth the secrets of her family’s past. As the dark forces gather around them, can Cassie protect all that she holds dear?</p><p>The fantastic debut novel from Lucy Hope, with cover illustration by Anna Shepeta.</p>",
    yearOfPublishing: new Date("2021"),
    duration: 380,
    genre: "children-literature"
  },
  {
    name: "In a Holidaze",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637421185/books/9781982123949-l_qftkqp.jpg"],
    quantity: 30,
    author: "619917e7fdd16e771992e734",
    categories: "ebooks",
    currentPrice: 5,
    publisher: "gallery-books",
    shortDescription: "It’s the most wonderful time of the year…but not for Maelyn Jones. She’s living with her parents, hates her going-nowhere job, and has just made a romantic error of epic proportions. But perhaps worst of all, this is the last Christmas Mae will be at her favorite place in the world—the snowy Utah cabin where she and her family have spent every holiday since she was born, along with two other beloved families. ",
    fullDescription: "<p>It’s the most wonderful time of the year…but not for Maelyn Jones. She’s living with her parents, hates her going-nowhere job, and has just made a romantic error of epic proportions.</p><p>But perhaps worst of all, this is the last Christmas Mae will be at her favorite place in the world—the snowy Utah cabin where she and her family have spent every holiday since she was born, along with two other beloved families. Mentally melting down as she drives away from the cabin for the final time, Mae throws out what she thinks is a simple plea to the universe: Please. Show me what will make me happy.</p><p>The next thing she knows, tires screech and metal collides, everything goes black. But when Mae gasps awake…she’s on an airplane bound for Utah, where she begins the same holiday all over again. With one hilarious disaster after another sending her back to the plane, Mae must figure out how to break free of the strange time loop—and finally get her true love under the mistletoe.</p><p>Jam-packed with yuletide cheer, an unforgettable cast of characters, and Christina Lauren’s trademark “downright hilarious” (Helen Hoang, author of The Bride Test) hijinks, this swoon-worthy romantic read will make you believe in the power of wishes and the magic of the holidays.</p>",
    yearOfPublishing: new Date("2020"),
    genre: "fiction",
    numberOfPages: 307
  },
  {
    name: "In a Holidaze",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637421185/books/9781982123949-l_qftkqp.jpg"],
    quantity: 30,
    author: "619917e7fdd16e771992e734",
    categories: "audio-books",
    currentPrice: 5,
    publisher: "gallery-books",
    shortDescription: "It’s the most wonderful time of the year…but not for Maelyn Jones. She’s living with her parents, hates her going-nowhere job, and has just made a romantic error of epic proportions. But perhaps worst of all, this is the last Christmas Mae will be at her favorite place in the world—the snowy Utah cabin where she and her family have spent every holiday since she was born, along with two other beloved families. ",
    fullDescription: "<p>It’s the most wonderful time of the year…but not for Maelyn Jones. She’s living with her parents, hates her going-nowhere job, and has just made a romantic error of epic proportions.</p><p>But perhaps worst of all, this is the last Christmas Mae will be at her favorite place in the world—the snowy Utah cabin where she and her family have spent every holiday since she was born, along with two other beloved families. Mentally melting down as she drives away from the cabin for the final time, Mae throws out what she thinks is a simple plea to the universe: Please. Show me what will make me happy.</p><p>The next thing she knows, tires screech and metal collides, everything goes black. But when Mae gasps awake…she’s on an airplane bound for Utah, where she begins the same holiday all over again. With one hilarious disaster after another sending her back to the plane, Mae must figure out how to break free of the strange time loop—and finally get her true love under the mistletoe.</p><p>Jam-packed with yuletide cheer, an unforgettable cast of characters, and Christina Lauren’s trademark “downright hilarious” (Helen Hoang, author of The Bride Test) hijinks, this swoon-worthy romantic read will make you believe in the power of wishes and the magic of the holidays.</p>",
    yearOfPublishing: new Date("2020"),
    genre: "fiction",
    duration: 409
  },
  {
    name: "In a Holidaze",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637421185/books/9781982123949-l_qftkqp.jpg"],
    quantity: 30,
    author: "619917e7fdd16e771992e734",
    categories: "paper-books",
    currentPrice: 10,
    publisher: "gallery-books",
    shortDescription: "It’s the most wonderful time of the year…but not for Maelyn Jones. She’s living with her parents, hates her going-nowhere job, and has just made a romantic error of epic proportions. But perhaps worst of all, this is the last Christmas Mae will be at her favorite place in the world—the snowy Utah cabin where she and her family have spent every holiday since she was born, along with two other beloved families. ",
    fullDescription: "<p>It’s the most wonderful time of the year…but not for Maelyn Jones. She’s living with her parents, hates her going-nowhere job, and has just made a romantic error of epic proportions.</p><p>But perhaps worst of all, this is the last Christmas Mae will be at her favorite place in the world—the snowy Utah cabin where she and her family have spent every holiday since she was born, along with two other beloved families. Mentally melting down as she drives away from the cabin for the final time, Mae throws out what she thinks is a simple plea to the universe: Please. Show me what will make me happy.</p><p>The next thing she knows, tires screech and metal collides, everything goes black. But when Mae gasps awake…she’s on an airplane bound for Utah, where she begins the same holiday all over again. With one hilarious disaster after another sending her back to the plane, Mae must figure out how to break free of the strange time loop—and finally get her true love under the mistletoe.</p><p>Jam-packed with yuletide cheer, an unforgettable cast of characters, and Christina Lauren’s trademark “downright hilarious” (Helen Hoang, author of The Bride Test) hijinks, this swoon-worthy romantic read will make you believe in the power of wishes and the magic of the holidays.</p>",
    yearOfPublishing: new Date("2020"),
    genre: "fiction",
    numberOfPages: 307,
    coverType: "soft",
  },
  {
    name: "The Honey-Don't List",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637433702/books/9781982123918-l_xxz1yd.jpg"],
    quantity: 150,
    author: "619917e7fdd16e771992e734",
    categories: "audio-books",
    currentPrice: 5,
    publisher: "gallery-books",
    shortDescription: "Carey Duncan has worked for home remodeling and design gurus Melissa and Rusty Tripp for nearly a decade. A country girl at heart, Carey started in their first store at sixteen, and - more than anyone would suspect - has helped them build an empire. With a new show and a book about to launch, the Tripps are on the verge of superstardom. There’s only one problem: America’s favorite couple can’t stand each other.",
    fullDescription: "<p>Carey Duncan has worked for home remodeling and design gurus Melissa and Rusty Tripp for nearly a decade. A country girl at heart, Carey started in their first store at sixteen, and - more than anyone would suspect - has helped them build an empire. With a new show and a book about to launch, the Tripps are on the verge of superstardom. There’s only one problem: America’s favorite couple can’t stand each other.</p><p>James McCann, MIT graduate and engineering genius, was originally hired as a structural engineer, but the job isn’t all he thought it’d be. The last straw? Both he and Carey must go on book tour with the Tripps and keep the wheels from falling off the proverbial bus.</p><p>Unfortunately, neither of them is in any position to quit. Carey needs health insurance, and James has been promised the role of a lifetime if he can just keep the couple on track for a few more weeks. While road-tripping with the Tripps up the West Coast, Carey and James vow to work together to keep their bosses’ secrets hidden, and their own jobs secure. But if they stop playing along - and start playing for keeps - they may have the chance to build something beautiful together…</p>",
    yearOfPublishing: new Date("2020"),
    genre: "fiction",
    duration: 400
  },
  {
    name: "The Honey-Don't List",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637433702/books/9781982123918-l_xxz1yd.jpg"],
    quantity: 50,
    author: "619917e7fdd16e771992e734",
    categories: "paper-books",
    currentPrice: 10,
    publisher: "gallery-books",
    shortDescription: "Carey Duncan has worked for home remodeling and design gurus Melissa and Rusty Tripp for nearly a decade. A country girl at heart, Carey started in their first store at sixteen, and - more than anyone would suspect - has helped them build an empire. With a new show and a book about to launch, the Tripps are on the verge of superstardom. There’s only one problem: America’s favorite couple can’t stand each other.",
    fullDescription: "<p>Carey Duncan has worked for home remodeling and design gurus Melissa and Rusty Tripp for nearly a decade. A country girl at heart, Carey started in their first store at sixteen, and - more than anyone would suspect - has helped them build an empire. With a new show and a book about to launch, the Tripps are on the verge of superstardom. There’s only one problem: America’s favorite couple can’t stand each other.</p><p>James McCann, MIT graduate and engineering genius, was originally hired as a structural engineer, but the job isn’t all he thought it’d be. The last straw? Both he and Carey must go on book tour with the Tripps and keep the wheels from falling off the proverbial bus.</p><p>Unfortunately, neither of them is in any position to quit. Carey needs health insurance, and James has been promised the role of a lifetime if he can just keep the couple on track for a few more weeks. While road-tripping with the Tripps up the West Coast, Carey and James vow to work together to keep their bosses’ secrets hidden, and their own jobs secure. But if they stop playing along - and start playing for keeps - they may have the chance to build something beautiful together…</p>",
    yearOfPublishing: new Date("2020"),
    genre: "fiction",
    numberOfPages: 308,
    coverType: "hard",
  },
  {
    name: "The Honey-Don't List",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637433702/books/9781982123918-l_xxz1yd.jpg"],
    quantity: 50,
    author: "619917e7fdd16e771992e734",
    categories: "paper-books",
    currentPrice: 10,
    publisher: "gallery-books",
    shortDescription: "Carey Duncan has worked for home remodeling and design gurus Melissa and Rusty Tripp for nearly a decade. A country girl at heart, Carey started in their first store at sixteen, and - more than anyone would suspect - has helped them build an empire. With a new show and a book about to launch, the Tripps are on the verge of superstardom. There’s only one problem: America’s favorite couple can’t stand each other.",
    fullDescription: "<p>Carey Duncan has worked for home remodeling and design gurus Melissa and Rusty Tripp for nearly a decade. A country girl at heart, Carey started in their first store at sixteen, and - more than anyone would suspect - has helped them build an empire. With a new show and a book about to launch, the Tripps are on the verge of superstardom. There’s only one problem: America’s favorite couple can’t stand each other.</p><p>James McCann, MIT graduate and engineering genius, was originally hired as a structural engineer, but the job isn’t all he thought it’d be. The last straw? Both he and Carey must go on book tour with the Tripps and keep the wheels from falling off the proverbial bus.</p><p>Unfortunately, neither of them is in any position to quit. Carey needs health insurance, and James has been promised the role of a lifetime if he can just keep the couple on track for a few more weeks. While road-tripping with the Tripps up the West Coast, Carey and James vow to work together to keep their bosses’ secrets hidden, and their own jobs secure. But if they stop playing along - and start playing for keeps - they may have the chance to build something beautiful together…</p>",
    yearOfPublishing: new Date("2020"),
    genre: "fiction",
    numberOfPages: 308,
    coverType: "hard",
  },
  {
    name: "How to Make the World Add Up: Ten Rules for Thinking Differently About Numbers",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637436733/books/9780349143866_llwrby.jpg"],
    quantity: 50,
    author: "61994c39cdfe2d8b4aa92547",
    categories: "paper-books",
    currentPrice: 10,
    publisher: "brown",
    shortDescription: "If you aren't in love with stats before reading this book, you will be by the time you're done. Powerful, persuasive, and in these truth-defying times, indispensable'Caroline Criado Perez, author of Invisible Women'Nobody makes the statistics of everyday life more fascinating and enjoyable than Tim Harford'Bill Bryson'Fabulously readable, lucid, witty and authoritative",
    fullDescription: "<p>If you aren't in love with stats before reading this book, you will be by the time you're done. Powerful, persuasive, and in these truth-defying times, indispensable'Caroline Criado Perez, author of Invisible Women'Nobody makes the statistics of everyday life more fascinating and enjoyable than Tim Harford'Bill Bryson'Fabulously readable, lucid, witty and authoritative</p><p>Every politician and journalist should be made to read this book, but everyone else will get so much pleasure and draw so much strength from the joyful way it dispels the clouds of deceit and delusion' Stephen Fry'Wise, humane and, above all, illuminating. Nobody is better on statistics and numbers - and how to make sense of them'Matthew SyedWhen was the last time you read a grand statement, accompanied by a large number, and wondered whether it could really be true Statistics are vital in helping us tell stories - we see them in the papers, on social media, and we hear them used in everyday conversation - and yet we doubt them more than ever. But numbers - in the right hands - have the power to change the world for the better.</p><p>Contrary to popular belief, good statistics are not a trick, although they are a kind of magic. Good statistics are not smoke and mirrors; in fact, they help us see more clearly. Good statistics are like a telescope for an astronomer, a microscope for a bacteriologist, or an X-ray for a radiologist. If we are willing to let them, good statistics help us see things about the world around us and about ourselves - both large and small - that we would not be able to see in any other way.</p><p>In How to Make the World Add Up, Tim Harford draws on his experience as both an economist and presenter of the BBC's radio show 'More or Less'. He takes us deep into the world of disinformation and obfuscation, bad research and misplaced motivation to find those priceless jewels of data and analysis that make communicating with numbers worthwhile</p>",
    yearOfPublishing: new Date("2020"),
    genre: "business-literature",
    numberOfPages: 304,
    coverType: "hard",
  },
  {
    name: "How to Make the World Add Up: Ten Rules for Thinking Differently About Numbers",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637436733/books/9780349143866_llwrby.jpg"],
    quantity: 100,
    author: "61994c39cdfe2d8b4aa92547",
    categories: "ebooks",
    currentPrice: 10,
    publisher: "brown",
    shortDescription: "If you aren't in love with stats before reading this book, you will be by the time you're done. Powerful, persuasive, and in these truth-defying times, indispensable'Caroline Criado Perez, author of Invisible Women'Nobody makes the statistics of everyday life more fascinating and enjoyable than Tim Harford'Bill Bryson'Fabulously readable, lucid, witty and authoritative",
    fullDescription: "<p>If you aren't in love with stats before reading this book, you will be by the time you're done. Powerful, persuasive, and in these truth-defying times, indispensable'Caroline Criado Perez, author of Invisible Women'Nobody makes the statistics of everyday life more fascinating and enjoyable than Tim Harford'Bill Bryson'Fabulously readable, lucid, witty and authoritative</p><p>Every politician and journalist should be made to read this book, but everyone else will get so much pleasure and draw so much strength from the joyful way it dispels the clouds of deceit and delusion' Stephen Fry'Wise, humane and, above all, illuminating. Nobody is better on statistics and numbers - and how to make sense of them'Matthew SyedWhen was the last time you read a grand statement, accompanied by a large number, and wondered whether it could really be true Statistics are vital in helping us tell stories - we see them in the papers, on social media, and we hear them used in everyday conversation - and yet we doubt them more than ever. But numbers - in the right hands - have the power to change the world for the better.</p><p>Contrary to popular belief, good statistics are not a trick, although they are a kind of magic. Good statistics are not smoke and mirrors; in fact, they help us see more clearly. Good statistics are like a telescope for an astronomer, a microscope for a bacteriologist, or an X-ray for a radiologist. If we are willing to let them, good statistics help us see things about the world around us and about ourselves - both large and small - that we would not be able to see in any other way.</p><p>In How to Make the World Add Up, Tim Harford draws on his experience as both an economist and presenter of the BBC's radio show 'More or Less'. He takes us deep into the world of disinformation and obfuscation, bad research and misplaced motivation to find those priceless jewels of data and analysis that make communicating with numbers worthwhile</p>",
    yearOfPublishing: new Date("2020"),
    genre: "business-literature",
    numberOfPages: 304
  },
  {
    name: "How to Make the World Add Up: Ten Rules for Thinking Differently About Numbers",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637436733/books/9780349143866_llwrby.jpg"],
    quantity: 100,
    author: "61994c39cdfe2d8b4aa92547",
    categories: "audio-books",
    currentPrice: 15,
    publisher: "brown",
    shortDescription: "If you aren't in love with stats before reading this book, you will be by the time you're done. Powerful, persuasive, and in these truth-defying times, indispensable'Caroline Criado Perez, author of Invisible Women'Nobody makes the statistics of everyday life more fascinating and enjoyable than Tim Harford'Bill Bryson'Fabulously readable, lucid, witty and authoritative",
    fullDescription: "<p>If you aren't in love with stats before reading this book, you will be by the time you're done. Powerful, persuasive, and in these truth-defying times, indispensable'Caroline Criado Perez, author of Invisible Women'Nobody makes the statistics of everyday life more fascinating and enjoyable than Tim Harford'Bill Bryson'Fabulously readable, lucid, witty and authoritative</p><p>Every politician and journalist should be made to read this book, but everyone else will get so much pleasure and draw so much strength from the joyful way it dispels the clouds of deceit and delusion' Stephen Fry'Wise, humane and, above all, illuminating. Nobody is better on statistics and numbers - and how to make sense of them'Matthew SyedWhen was the last time you read a grand statement, accompanied by a large number, and wondered whether it could really be true Statistics are vital in helping us tell stories - we see them in the papers, on social media, and we hear them used in everyday conversation - and yet we doubt them more than ever. But numbers - in the right hands - have the power to change the world for the better.</p><p>Contrary to popular belief, good statistics are not a trick, although they are a kind of magic. Good statistics are not smoke and mirrors; in fact, they help us see more clearly. Good statistics are like a telescope for an astronomer, a microscope for a bacteriologist, or an X-ray for a radiologist. If we are willing to let them, good statistics help us see things about the world around us and about ourselves - both large and small - that we would not be able to see in any other way.</p><p>In How to Make the World Add Up, Tim Harford draws on his experience as both an economist and presenter of the BBC's radio show 'More or Less'. He takes us deep into the world of disinformation and obfuscation, bad research and misplaced motivation to find those priceless jewels of data and analysis that make communicating with numbers worthwhile</p>",
    yearOfPublishing: new Date("2020"),
    genre: "business-literature",
    duration: 390
  },
  {
    name: "The Next Fifty Things that Made the Modern Economy",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637438116/books/9780349144030_rxldtg.jpg"],
    quantity: 100,
    author: "61994c39cdfe2d8b4aa92547",
    categories: "audio-books",
    currentPrice: 5,
    publisher: "brown",
    shortDescription: "Following on from the brilliant Fifty Things That Made the Modern Economy, the bestselling economist Tim Harford explores another fifty items – from bricks to postage stamps – that have played a key role in shaping our global story.",
    fullDescription: "<p>In Fifty Things that Made the Modern Economy, the revolutionary, acclaimed book, radio series and podcast, bestselling economist Tim Harford introduced us to a selection of fifty radical inventions that changed the world.</p><p>Now, in this new book, Harford once again brings us an array of remarkable, memorable, curious and often unexpected 'things' - inventions that teach us lessons by turns intimate and sweeping about the complex world economy we live in today.</p><p>From the brick, blockchain and the bicycle to fire, the factory and fundraising, and from solar PV and the pencil to the postage stamp, this brilliant and enlightening collection resonates, fascinates and stimulates. It is a wonderful blend of insight and inspiration from one of Britain's finest non-fiction storytellers.</p>",
    yearOfPublishing: new Date("2021"),
    genre: "business-literature",
    duration: 469
  },
  {
    name: "The Next Fifty Things that Made the Modern Economy",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637438116/books/9780349144030_rxldtg.jpg"],
    quantity: 100,
    author: "61994c39cdfe2d8b4aa92547",
    categories: "ebooks",
    currentPrice: 5,
    publisher: "brown",
    shortDescription: "Following on from the brilliant Fifty Things That Made the Modern Economy, the bestselling economist Tim Harford explores another fifty items – from bricks to postage stamps – that have played a key role in shaping our global story.",
    fullDescription: "<p>In Fifty Things that Made the Modern Economy, the revolutionary, acclaimed book, radio series and podcast, bestselling economist Tim Harford introduced us to a selection of fifty radical inventions that changed the world.</p><p>Now, in this new book, Harford once again brings us an array of remarkable, memorable, curious and often unexpected 'things' - inventions that teach us lessons by turns intimate and sweeping about the complex world economy we live in today.</p><p>From the brick, blockchain and the bicycle to fire, the factory and fundraising, and from solar PV and the pencil to the postage stamp, this brilliant and enlightening collection resonates, fascinates and stimulates. It is a wonderful blend of insight and inspiration from one of Britain's finest non-fiction storytellers.</p>",
    yearOfPublishing: new Date("2021"),
    genre: "business-literature",
    numberOfPages: 352
  },
  {
    name: "The Next Fifty Things that Made the Modern Economy",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637438116/books/9780349144030_rxldtg.jpg"],
    quantity: 100,
    author: "61994c39cdfe2d8b4aa92547",
    categories: "paper-books",
    currentPrice: 15,
    publisher: "brown",
    shortDescription: "Following on from the brilliant Fifty Things That Made the Modern Economy, the bestselling economist Tim Harford explores another fifty items – from bricks to postage stamps – that have played a key role in shaping our global story.",
    fullDescription: "<p>In Fifty Things that Made the Modern Economy, the revolutionary, acclaimed book, radio series and podcast, bestselling economist Tim Harford introduced us to a selection of fifty radical inventions that changed the world.</p><p>Now, in this new book, Harford once again brings us an array of remarkable, memorable, curious and often unexpected 'things' - inventions that teach us lessons by turns intimate and sweeping about the complex world economy we live in today.</p><p>From the brick, blockchain and the bicycle to fire, the factory and fundraising, and from solar PV and the pencil to the postage stamp, this brilliant and enlightening collection resonates, fascinates and stimulates. It is a wonderful blend of insight and inspiration from one of Britain's finest non-fiction storytellers.</p>",
    yearOfPublishing: new Date("2021"),
    genre: "business-literature",
    numberOfPages: 352,
    coverType: "hard",
  },
  {
    name: "The Data Detective: Ten Easy Rules to Make Sense of Statistics",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637438819/books/41GD6oSy8PL_wbrrfa.jpg"],
    quantity: 300,
    author: "61994c39cdfe2d8b4aa92547",
    categories: "paper-books",
    currentPrice: 10,
    publisher: "riverhead-books",
    shortDescription: "Today we think statistics are the enemy, numbers used to mislead and confuse us. That’s a mistake, Tim Harford says in The Data Detective. We shouldn’t be suspicious of statistics—we need to understand what they mean and how they can improve our lives: they are, at heart, human behavior seen through the prism of numbers and are often “the only way of grasping much of what is going on around us.",
    fullDescription: "<p>Today we think statistics are the enemy, numbers used to mislead and confuse us. That’s a mistake, Tim Harford says in The Data Detective. We shouldn’t be suspicious of statistics—we need to understand what they mean and how they can improve our lives: they are, at heart, human behavior seen through the prism of numbers and are often “the only way of grasping much of what is going on around us.</p><p>If we can toss aside our fears and learn to approach them clearly—understanding how our own preconceptions lead us astray—statistics can point to ways we can live better and work smarter.</p><p>As “perhaps the best popular economics writer in the world” (New Statesman), Tim Harford is an expert at taking complicated ideas and untangling them for millions of readers. In The Data Detective, he uses new research in science and psychology to set out ten strategies for using statistics to erase our biases and replace them with new ideas that use virtues like patience, curiosity, and good sense to better understand ourselves and the world.</p><p>As a result, The Data Detective is a big-idea book about statistics and human behavior that is fresh, unexpected, and insightful.</p>",
    yearOfPublishing: new Date("2021"),
    genre: "business-literature",
    numberOfPages: 334,
    coverType: "soft",
  },
  {
    name: "The Data Detective: Ten Easy Rules to Make Sense of Statistics",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637438819/books/41GD6oSy8PL_wbrrfa.jpg"],
    quantity: 300,
    author: "61994c39cdfe2d8b4aa92547",
    categories: "ebooks",
    currentPrice: 5,
    publisher: "riverhead-books",
    shortDescription: "Today we think statistics are the enemy, numbers used to mislead and confuse us. That’s a mistake, Tim Harford says in The Data Detective. We shouldn’t be suspicious of statistics—we need to understand what they mean and how they can improve our lives: they are, at heart, human behavior seen through the prism of numbers and are often “the only way of grasping much of what is going on around us.",
    fullDescription: "<p>Today we think statistics are the enemy, numbers used to mislead and confuse us. That’s a mistake, Tim Harford says in The Data Detective. We shouldn’t be suspicious of statistics—we need to understand what they mean and how they can improve our lives: they are, at heart, human behavior seen through the prism of numbers and are often “the only way of grasping much of what is going on around us.</p><p>If we can toss aside our fears and learn to approach them clearly—understanding how our own preconceptions lead us astray—statistics can point to ways we can live better and work smarter.</p><p>As “perhaps the best popular economics writer in the world” (New Statesman), Tim Harford is an expert at taking complicated ideas and untangling them for millions of readers. In The Data Detective, he uses new research in science and psychology to set out ten strategies for using statistics to erase our biases and replace them with new ideas that use virtues like patience, curiosity, and good sense to better understand ourselves and the world.</p><p>As a result, The Data Detective is a big-idea book about statistics and human behavior that is fresh, unexpected, and insightful.</p>",
    yearOfPublishing: new Date("2021"),
    genre: "business-literature",
    numberOfPages: 334
  },
  {
    name: "Harry Potter and the Order of the Phoenix",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637501674/books/1011963752_w919_h430_harry-potter-and_cvjdli.jpg"],
    quantity: 100,
    author: "619a488fcc615cae5b11bf74",
    categories: "ebooks",
    currentPrice: 10,
    publisher: "bloomsbury-press",
    shortDescription: "Dark times have come to Hogwarts. After the Dementors' attack on his cousin Dudley, Harry Potter knows that Voldemort will stop at nothing to find him. There are many who deny the Dark Lord's return, but Harry is not alone: a secret order gathers at Grimmauld Place to fight against the Dark forces. ",
    fullDescription: "<p>‘The headquarters of the Order of the Phoenix may be found at number twelve, Grimmauld Place, London.’</p><p>The wizarding world is divided; Lord Voldemort has returned in secret and not everyone believes Harry’s account of what happened to him in the final moments of the Triwizard Tournament. More alone than ever, Harry finds himself an enemy of The Ministry of Magic as it seeks to have an ever-more sinister control over Hogwarts. For the school is now under the governance of the ruthless, sugar-pink-clad, Dolores Umbridge who is intent on bringing her own brand of order to the school, using increasingly brutal methods.</p><p>There are those who are fighting back, the secret society of The Order of the Phoenix but this puts those Harry loves most in mortal danger. At school, Harry and his friends must also learn to defend themselves against the enemy and Harry most of all, for Voldemort is stealing into his mind, and he is getting stronger. Only Harry’s enemy, Severus Snape, can teach him to protect himself but will he learn what he needs in time and will it be enough to stand against the deadliest of wizards?</p><p>As Harry enters his fifth year at Hogwarts, Waterstones beckons you to see the darker side of the wizarding world. Enter the Department of Mysteries, see what lies in Dumbledore’s most hidden memories and prepare to face the enemy within.</p><p>“The Harry Potter books have already created a corpus of modern legend that their young fans will remember long into their autumn years, not merely in the story they tell but in the phenomenon that has grown around them.” The Guardian</p>",
    yearOfPublishing: new Date("2014"),
    genre: "adventures",
    numberOfPages: 816
  },
  {
    name: "Harry Potter and the Order of the Phoenix",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637501674/books/1011963752_w919_h430_harry-potter-and_cvjdli.jpg"],
    quantity: 100,
    author: "619a488fcc615cae5b11bf74",
    categories: "paper-books",
    currentPrice: 20,
    publisher: "bloomsbury-press",
    shortDescription: "Dark times have come to Hogwarts. After the Dementors' attack on his cousin Dudley, Harry Potter knows that Voldemort will stop at nothing to find him. There are many who deny the Dark Lord's return, but Harry is not alone: a secret order gathers at Grimmauld Place to fight against the Dark forces. ",
    fullDescription: "<p>‘The headquarters of the Order of the Phoenix may be found at number twelve, Grimmauld Place, London.’</p><p>The wizarding world is divided; Lord Voldemort has returned in secret and not everyone believes Harry’s account of what happened to him in the final moments of the Triwizard Tournament. More alone than ever, Harry finds himself an enemy of The Ministry of Magic as it seeks to have an ever-more sinister control over Hogwarts. For the school is now under the governance of the ruthless, sugar-pink-clad, Dolores Umbridge who is intent on bringing her own brand of order to the school, using increasingly brutal methods.</p><p>There are those who are fighting back, the secret society of The Order of the Phoenix but this puts those Harry loves most in mortal danger. At school, Harry and his friends must also learn to defend themselves against the enemy and Harry most of all, for Voldemort is stealing into his mind, and he is getting stronger. Only Harry’s enemy, Severus Snape, can teach him to protect himself but will he learn what he needs in time and will it be enough to stand against the deadliest of wizards?</p><p>As Harry enters his fifth year at Hogwarts, Waterstones beckons you to see the darker side of the wizarding world. Enter the Department of Mysteries, see what lies in Dumbledore’s most hidden memories and prepare to face the enemy within.</p><p>“The Harry Potter books have already created a corpus of modern legend that their young fans will remember long into their autumn years, not merely in the story they tell but in the phenomenon that has grown around them.” The Guardian</p>",
    yearOfPublishing: new Date("2014"),
    genre: "adventures",
    numberOfPages: 816,
    coverType: "soft",
  },
  {
    name: "Harry Potter and the Goblet of Fire",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637502559/books/51Vjb2qJwzL_urpbfm.jpg"],
    quantity: 100,
    author: "619a488fcc615cae5b11bf74",
    categories: "paper-books",
    currentPrice: 25,
    publisher: "Bloomsbury Publishing PLC",
    shortDescription: "Harry Potter’s fourteenth year is proving to be a memorable one, not only is it the four hundred and twenty-second Quidditch World Cup but Hogwarts is playing host to its own unique wizarding competition, the Triwizard Tournament.",
    fullDescription: "<p>Harry Potter’s fourteenth year is proving to be a memorable one, not only is it the four hundred and twenty-second Quidditch World Cup but Hogwarts is playing host to its own unique wizarding competition, the Triwizard Tournament.</p><p>The school finds itself playing host to two visiting magical schools – the enchanting Beauxbatons Academy and the formidable Durmstrang Institute. Only three of the bravest witches or wizards over the age of seventeen may compete; their names to be drawn out of the enticing, golden Triwizard Cup.</p><p>But this is no Quidditch match, the reward is glory but the perils are lethal and somebody has other plans in store. For when the time comes, the unthinkable happens; an extra name is recalled from the cup, Harry Potter’s name. </p><p>Now Harry is fighting for more than victory, he is battling for his life, against an unseen sinister force. With even his friends doubting him, Harry finds himself more alone than ever and in the greatest of danger.</p><p>The map of the wizarding world unfolds in this gripping fourth novel in the award-winning Harry Potter series. Waterstones invites you to compete alongside Harry as he faces fire-breathing dragons, delves to the deepest depths of the lake and (most dauntingly of all) learns to dance. This will be a parting of the ways, for after this, nothing can ever be the same again.</p>",
    yearOfPublishing: new Date("2014"),
    genre: "adventures",
    numberOfPages: 640,
    coverType: "soft"
  },
  {
    name: "The Christmas Pig",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637503163/books/9781444964912_gp95he.jpg"],
    quantity: 100,
    author: "619a488fcc615cae5b11bf74",
    categories: "paper-books",
    currentPrice: 15,
    publisher: "penguin-house",
    shortDescription: "Bursting with festive charm and imagination, this magical adventure written by J.K. Rowling and illustrated by Jim Field, revolves around a boy’s determined quest to find his missing toy pig before Christmas Day.",
    fullDescription: "<p>One boy and his toy are about to change everything…</p><p>Jack loves his childhood toy, Dur Pig. DP has always been there for him, through good and bad. Until one Christmas Eve something terrible happens – DP is lost. But Christmas Eve is a night for miracles and lost causes, a night when all things can come to life… even toys. And Jack’s newest toy – the Christmas Pig (DP’s annoying replacement) – has a daring plan: Together they’ll embark on a magical journey to seek something lost, and to save the best friend Jack has ever known…</p><p>A heartwarming, page-turning adventure about one child’s love for his most treasured thing, and how far he will go to find it. A tale for the whole family to fall in love with, from one of the world’s greatest storytellers.</p><p>A gorgeously gifty hardback, with full-colour jacket and featuring 9 black and white spreads and decorative inside art from renowned illustrator, Jim Field.</p>",
    yearOfPublishing: new Date("2021"),
    genre: "adventures",
    numberOfPages: 288,
    coverType: "hard"
  },
  {
    name: "The Christmas Pig",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637503163/books/9781444964912_gp95he.jpg"],
    quantity: 300,
    author: "619a488fcc615cae5b11bf74",
    categories: "audio-books",
    currentPrice: 5,
    publisher: "hachette-children-group",
    shortDescription: "Bursting with festive charm and imagination, this magical adventure written by J.K. Rowling and illustrated by Jim Field, revolves around a boy’s determined quest to find his missing toy pig before Christmas Day.",
    fullDescription: "<p>One boy and his toy are about to change everything…</p><p>Jack loves his childhood toy, Dur Pig. DP has always been there for him, through good and bad. Until one Christmas Eve something terrible happens – DP is lost. But Christmas Eve is a night for miracles and lost causes, a night when all things can come to life… even toys. And Jack’s newest toy – the Christmas Pig (DP’s annoying replacement) – has a daring plan: Together they’ll embark on a magical journey to seek something lost, and to save the best friend Jack has ever known…</p><p>A heartwarming, page-turning adventure about one child’s love for his most treasured thing, and how far he will go to find it. A tale for the whole family to fall in love with, from one of the world’s greatest storytellers.</p><p>A gorgeously gifty hardback, with full-colour jacket and featuring 9 black and white spreads and decorative inside art from renowned illustrator, Jim Field.</p>",
    yearOfPublishing: new Date("2021"),
    genre: "adventures",
    duration: 384,
  },
  {
    name: "Murder Most Unladylike - A Murder Most Unladylike Mystery",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637509442/books/9780141369761_lcbbiz.jpg"],
    quantity: 100,
    author: "619a67d9c9a653c13ffbe3eb",
    categories: "paper-books",
    currentPrice: 8,
    publisher: "penguin-house",
    shortDescription: "The first instalment of the hugely popular Wells and Wong detective stories for children, Stevens’s note-perfect pastiche of Golden Age crime mysteries is a brilliantly realised and compelling boarding school adventure. ",
    fullDescription: "<p>The first marvellous murder mystery in the bestselling Murder Most Unladylike series!</p><p>At Deepdean School for Girls, Daisy Wells and Hazel Wong have set up their own detective agency. But they are struggling to find any real crimes to investigate. (Unless you count the case of Lavinia's missing tie. Which they don't.)</p><p>Then Hazel discovers the Science Mistress, Miss Bell, lying dead in the Gym. To add to the mystery, when she and Daisy return five minutes later, the body has disappeared. Now Hazel and Daisy not only have a murder to solve: they have to prove one happened in the first place.</p><p>Determined to get to the bottom of the crime before the killer strikes again Hazel and Daisy must hunt for evidence, spy on their suspects and use all the cunning and intuition they can muster. But will they succeed? And can their friendship stand the test?</p>",
    yearOfPublishing: new Date("2016"),
    genre: "adventures",
    numberOfPages: 352,
    coverType: "soft"
  },
  {
    name: "Once Upon a Crime",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637509449/books/9780241419830_nbsu1p.jpg"],
    quantity: 100,
    author: "619a67d9c9a653c13ffbe3eb",
    categories: "paper-books",
    currentPrice: 18,
    publisher: "penguin-house",
    shortDescription: "Relive the crime-busting awesomeness of Wells and Wong one last time with this enthralling, playful and wildly entertaining collection of stories from the files of Murder Most Unladylike. A brand-new short story collection in the number-one bestselling award-winning Murder Most Unladylike series.",
    fullDescription: "<p>Featuring four original, never-before published stories, this incredible collection brings together Daisy Wells, Hazel Wong and their friends Alexander and George, as well as Hazel's sisters, Rose and May Wong.</p><p>From the artfully sinister The Case of the Second Scream, set aboard the ship carrying Daisy and Hazel's back from Hong Kong, to The Case of the Uninvited Guest, where a Uncle Felix and Aunt Lucy's wedding ceremony is the target for an unlikely threat.</p><p>The Hound of Weston School sees the Junior Pinkerton's lead the detecting, and May Wong steps up and shows her ambition to be the greatest spy ever when war breaks out in The Case of the Deadly Flat.</p><p>The perfect book for all Detective Society fans and avid readers of the Murder Most Unladylike series.</p>",
    yearOfPublishing: new Date("2021"),
    genre: "adventures",
    numberOfPages: 336,
    coverType: "soft"
  },
  {
    name: "Murder Most Unladylike - A Murder Most Unladylike Mystery",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637509442/books/9780141369761_lcbbiz.jpg"],
    quantity: 100,
    author: "619a67d9c9a653c13ffbe3eb",
    categories: "ebooks",
    currentPrice: 8,
    publisher: "penguin-house",
    shortDescription: "The first instalment of the hugely popular Wells and Wong detective stories for children, Stevens’s note-perfect pastiche of Golden Age crime mysteries is a brilliantly realised and compelling boarding school adventure. ",
    fullDescription: "<p>The first marvellous murder mystery in the bestselling Murder Most Unladylike series!</p><p>At Deepdean School for Girls, Daisy Wells and Hazel Wong have set up their own detective agency. But they are struggling to find any real crimes to investigate. (Unless you count the case of Lavinia's missing tie. Which they don't.)</p><p>Then Hazel discovers the Science Mistress, Miss Bell, lying dead in the Gym. To add to the mystery, when she and Daisy return five minutes later, the body has disappeared. Now Hazel and Daisy not only have a murder to solve: they have to prove one happened in the first place.</p><p>Determined to get to the bottom of the crime before the killer strikes again Hazel and Daisy must hunt for evidence, spy on their suspects and use all the cunning and intuition they can muster. But will they succeed? And can their friendship stand the test?</p>",
    yearOfPublishing: new Date("2016"),
    genre: "adventures",
    numberOfPages: 352
  },
  {
    name: "Once Upon a Crime",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637509449/books/9780241419830_nbsu1p.jpg"],
    quantity: 100,
    author: "619a67d9c9a653c13ffbe3eb",
    categories: "paper-books",
    currentPrice: 25,
    publisher: "penguin-house",
    shortDescription: "Relive the crime-busting awesomeness of Wells and Wong one last time with this enthralling, playful and wildly entertaining collection of stories from the files of Murder Most Unladylike. A brand-new short story collection in the number-one bestselling award-winning Murder Most Unladylike series.",
    fullDescription: "<p>Featuring four original, never-before published stories, this incredible collection brings together Daisy Wells, Hazel Wong and their friends Alexander and George, as well as Hazel's sisters, Rose and May Wong.</p><p>From the artfully sinister The Case of the Second Scream, set aboard the ship carrying Daisy and Hazel's back from Hong Kong, to The Case of the Uninvited Guest, where a Uncle Felix and Aunt Lucy's wedding ceremony is the target for an unlikely threat.</p><p>The Hound of Weston School sees the Junior Pinkerton's lead the detecting, and May Wong steps up and shows her ambition to be the greatest spy ever when war breaks out in The Case of the Deadly Flat.</p><p>The perfect book for all Detective Society fans and avid readers of the Murder Most Unladylike series.</p>",
    yearOfPublishing: new Date("2021"),
    genre: "adventures",
    numberOfPages: 336,
    coverType: "soft"
  },
  {
    name: "Surrounded by Idiots",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637519150/books/41rWzmdpuiL_lxo0h1.jpg"],
    quantity: 300,
    author: "619a8c932b77b7d09028ea9a",
    categories: "paper-books",
    currentPrice: 20,
    previousPrice: 25,
    publisher: "martin-essentials",
    shortDescription: "Do you ever think you’re the only one making any sense? Or tried to reason with your partner with disastrous results? Do long, rambling answers drive you crazy? Or does your colleague’s abrasive manner rub you the wrong way? You are not alone.",
    fullDescription: "<p>Do you ever think you’re the only one making any sense? Or tried to reason with your partner with disastrous results? Do long, rambling answers drive you crazy? Or does your colleague’s abrasive manner rub you the wrong way?</p><p>You are not alone. After a disastrous meeting with a highly successful entrepreneur, who was genuinely convinced he was ‘surrounded by idiots’, communication expert and bestselling author, Thomas Erikson dedicated himself to understanding how people function and why we often struggle to connect with certain types of people.</p><p>Surrounded by Idiots is an international phenomenon, selling over 1.5 million copies worldwide. It offers a simple, yet ground-breaking method for assessing the personalities of people we communicate with – in and out of the office – based on four personality types (Red, Blue, Green and Yellow), and provides insights into how we can adjust the way we speak and share information.</p><p>Erikson will help you understand yourself better, hone communication and social skills, handle conflict with confidence, improve dynamics with your boss and team, and get the best out of the people you deal with and manage. He also shares simple tricks on body language, improving written communication, advice on when to back away or when to push on, and when to speak up or shut up. Packed with ‘aha!’ and ‘oh no!’ moments, Surrounded by Idiots will help you understand and communicate with those around you, even people you currently think are beyond all comprehension. And with a bit of luck you can also be confident that the idiot out there isn’t you!</p>",
    yearOfPublishing: new Date("2019"),
    genre: "non-fiction",
    numberOfPages: 293,
    coverType: "hard"
  },
  {
    name: "Surrounded by Idiots",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637519150/books/41rWzmdpuiL_lxo0h1.jpg"],
    quantity: 100,
    author: "619a8c932b77b7d09028ea9a",
    categories: "audio-books",
    currentPrice: 10,
    publisher: "martin-essentials",
    shortDescription: "Do you ever think you’re the only one making any sense? Or tried to reason with your partner with disastrous results? Do long, rambling answers drive you crazy? Or does your colleague’s abrasive manner rub you the wrong way? You are not alone.",
    fullDescription: "<p>Do you ever think you’re the only one making any sense? Or tried to reason with your partner with disastrous results? Do long, rambling answers drive you crazy? Or does your colleague’s abrasive manner rub you the wrong way?</p><p>You are not alone. After a disastrous meeting with a highly successful entrepreneur, who was genuinely convinced he was ‘surrounded by idiots’, communication expert and bestselling author, Thomas Erikson dedicated himself to understanding how people function and why we often struggle to connect with certain types of people.</p><p>Surrounded by Idiots is an international phenomenon, selling over 1.5 million copies worldwide. It offers a simple, yet ground-breaking method for assessing the personalities of people we communicate with – in and out of the office – based on four personality types (Red, Blue, Green and Yellow), and provides insights into how we can adjust the way we speak and share information.</p><p>Erikson will help you understand yourself better, hone communication and social skills, handle conflict with confidence, improve dynamics with your boss and team, and get the best out of the people you deal with and manage. He also shares simple tricks on body language, improving written communication, advice on when to back away or when to push on, and when to speak up or shut up. Packed with ‘aha!’ and ‘oh no!’ moments, Surrounded by Idiots will help you understand and communicate with those around you, even people you currently think are beyond all comprehension. And with a bit of luck you can also be confident that the idiot out there isn’t you!</p>",
    yearOfPublishing: new Date("2019"),
    genre: "non-fiction",
    duration: 390
  },
  {
    name: "Surrounded by Idiots",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637519150/books/41rWzmdpuiL_lxo0h1.jpg"],
    quantity: 100,
    author: "619a8c932b77b7d09028ea9a",
    categories: "ebooks",
    currentPrice: 10,
    publisher: "martin-essentials",
    shortDescription: "Do you ever think you’re the only one making any sense? Or tried to reason with your partner with disastrous results? Do long, rambling answers drive you crazy? Or does your colleague’s abrasive manner rub you the wrong way? You are not alone.",
    fullDescription: "<p>Do you ever think you’re the only one making any sense? Or tried to reason with your partner with disastrous results? Do long, rambling answers drive you crazy? Or does your colleague’s abrasive manner rub you the wrong way?</p><p>You are not alone. After a disastrous meeting with a highly successful entrepreneur, who was genuinely convinced he was ‘surrounded by idiots’, communication expert and bestselling author, Thomas Erikson dedicated himself to understanding how people function and why we often struggle to connect with certain types of people.</p><p>Surrounded by Idiots is an international phenomenon, selling over 1.5 million copies worldwide. It offers a simple, yet ground-breaking method for assessing the personalities of people we communicate with – in and out of the office – based on four personality types (Red, Blue, Green and Yellow), and provides insights into how we can adjust the way we speak and share information.</p><p>Erikson will help you understand yourself better, hone communication and social skills, handle conflict with confidence, improve dynamics with your boss and team, and get the best out of the people you deal with and manage. He also shares simple tricks on body language, improving written communication, advice on when to back away or when to push on, and when to speak up or shut up. Packed with ‘aha!’ and ‘oh no!’ moments, Surrounded by Idiots will help you understand and communicate with those around you, even people you currently think are beyond all comprehension. And with a bit of luck you can also be confident that the idiot out there isn’t you!</p>",
    yearOfPublishing: new Date("2019"),
    numberOfPages: 293,
    genre: "non-fiction"
  },
  {
    name: "Surrounded by Psychopaths",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637519073/books/419iPuElzCS_kmv4iu.jpg"],
    quantity: 100,
    author: "619a8c932b77b7d09028ea9a",
    categories: "ebooks",
    currentPrice: 10,
    previousPrice: 15,
    publisher: "martin-essentials",
    shortDescription: "#1 internationally bestselling author Thomas Erikson shows readers how to identify and avoid the psychopaths around them.",
    fullDescription: "<p>Charming, charismatic, and delightful or manipulative, self-serving, and cunning? Psychopaths are both and that’s exactly what makes them dangerous. Bestselling author of the international phenomenon Surrounded by Idiots, Thomas Erikson reveals how to identify the psychopaths in your life and combat their efforts to control and manipulate.</p><p>Using the same simple four-color system of behavior classification that made Surrounded by Idiots so popular, Surrounded by Psychopaths teaches readers how to deal with psychopaths in their lives by becoming aware of their own behavior and their weaknesses. Vivid example stories illustrate ways that psychopaths can take advantage of various behavior types, helping readers identify their own weaknesses and be proactive about protecting themselves.</p><p>Erikson outlines some of the most common forms of manipulation used by psychopaths—and others—to influence those around them. Since manipulation can often be a feature of ordinary, non-psychopathic relationships, the book also includes practical methods and techniques to help readers confront controlling people and rehabilitate negative relationships into mutually respectful ones.</p><p>By understanding your behavior as well as the tendencies and strategies of psychopaths, Surrounded by Psychopaths will teach you to protect yourself from manipulative influence in your workplace, social life, and family.</p>",
    yearOfPublishing: new Date("2020"),
    numberOfPages: 260,
    genre: "non-fiction"
  },
  {
    name: "Surrounded by Psychopaths",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637519073/books/419iPuElzCS_kmv4iu.jpg"],
    quantity: 100,
    author: "619a8c932b77b7d09028ea9a",
    categories: "paper-books",
    currentPrice: 20,
    previousPrice: 15,
    publisher: "martin-essentials",
    shortDescription: "#1 internationally bestselling author Thomas Erikson shows readers how to identify and avoid the psychopaths around them.",
    fullDescription: "<p>Charming, charismatic, and delightful or manipulative, self-serving, and cunning? Psychopaths are both and that’s exactly what makes them dangerous. Bestselling author of the international phenomenon Surrounded by Idiots, Thomas Erikson reveals how to identify the psychopaths in your life and combat their efforts to control and manipulate.</p><p>Using the same simple four-color system of behavior classification that made Surrounded by Idiots so popular, Surrounded by Psychopaths teaches readers how to deal with psychopaths in their lives by becoming aware of their own behavior and their weaknesses. Vivid example stories illustrate ways that psychopaths can take advantage of various behavior types, helping readers identify their own weaknesses and be proactive about protecting themselves.</p><p>Erikson outlines some of the most common forms of manipulation used by psychopaths—and others—to influence those around them. Since manipulation can often be a feature of ordinary, non-psychopathic relationships, the book also includes practical methods and techniques to help readers confront controlling people and rehabilitate negative relationships into mutually respectful ones.</p><p>By understanding your behavior as well as the tendencies and strategies of psychopaths, Surrounded by Psychopaths will teach you to protect yourself from manipulative influence in your workplace, social life, and family.</p>",
    yearOfPublishing: new Date("2020"),
    numberOfPages: 260,
    genre: "non-fiction",
    coverType: "hard"
  },
  {
    name: "Surrounded by Psychopaths",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637519073/books/419iPuElzCS_kmv4iu.jpg"],
    quantity: 300,
    author: "619a8c932b77b7d09028ea9a",
    categories: "audio-books",
    currentPrice: 10,
    publisher: "martin-essentials",
    shortDescription: "#1 internationally bestselling author Thomas Erikson shows readers how to identify and avoid the psychopaths around them.",
    fullDescription: "<p>Charming, charismatic, and delightful or manipulative, self-serving, and cunning? Psychopaths are both and that’s exactly what makes them dangerous. Bestselling author of the international phenomenon Surrounded by Idiots, Thomas Erikson reveals how to identify the psychopaths in your life and combat their efforts to control and manipulate.</p><p>Using the same simple four-color system of behavior classification that made Surrounded by Idiots so popular, Surrounded by Psychopaths teaches readers how to deal with psychopaths in their lives by becoming aware of their own behavior and their weaknesses. Vivid example stories illustrate ways that psychopaths can take advantage of various behavior types, helping readers identify their own weaknesses and be proactive about protecting themselves.</p><p>Erikson outlines some of the most common forms of manipulation used by psychopaths—and others—to influence those around them. Since manipulation can often be a feature of ordinary, non-psychopathic relationships, the book also includes practical methods and techniques to help readers confront controlling people and rehabilitate negative relationships into mutually respectful ones.</p><p>By understanding your behavior as well as the tendencies and strategies of psychopaths, Surrounded by Psychopaths will teach you to protect yourself from manipulative influence in your workplace, social life, and family.</p>",
    yearOfPublishing: new Date("2020"),
    genre: "non-fiction",
    duration: 340
  },
  {
    name: "Surrounded by Bad Bosses (And Lazy Employees)",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637519065/books/41p2MHIa_tL_h0mfvp.jpg"],
    quantity: 200,
    author: "619a8c932b77b7d09028ea9a",
    categories: "audio-books",
    currentPrice: 10,
    publisher: "martin-essentials",
    shortDescription: "Internationally bestselling author Thomas Erikson has helped changed how the world thinks about behavior using a simple 4-color behavior analysis system. In Surrounded by Bad Bosses he applies that same system to revolutionize the workplace.",
    fullDescription: "<p>Internationally bestselling author Thomas Erikson has helped changed how the world thinks about behavior using a simple 4-color behavior analysis system. In Surrounded by Bad Bosses he applies that same system to revolutionize the workplace.</p><p>Everyone has had a bad boss. You might have one right now. You might even be one. Bad bosses are a fact of the workplace, whether they’re short-tempered, unclear about expectations, or too disorganized to manage so much as a stapler. But how do you not only survive a difficult boss, but help your career thrive despite them?</p><p>By identifying your boss’s behavior profile you’ll be better able to interact with them no matter what the situation. Erikson offers example stories and concrete steps to help you thrive in any work situation.</p><p>Of course, much as we love to blame our bosses, sometimes management isn’t the problem at all. For every bad boss there is also a lazy employee, so Erikson also looks at the issue from a completely different perspective—employees themselves— and explores why some colleagues frequently underachieve, and what you can do to change this if you're the boss.</p>",
    yearOfPublishing: new Date("2020"),
    genre: "non-fiction",
    duration: 520
  },
  {
    name: "Surrounded by Bad Bosses (And Lazy Employees)",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637519065/books/41p2MHIa_tL_h0mfvp.jpg"],
    quantity: 200,
    author: "619a8c932b77b7d09028ea9a",
    categories: "ebooks",
    currentPrice: 10,
    publisher: "martin-essentials",
    shortDescription: "Internationally bestselling author Thomas Erikson has helped changed how the world thinks about behavior using a simple 4-color behavior analysis system. In Surrounded by Bad Bosses he applies that same system to revolutionize the workplace.",
    fullDescription: "<p>Internationally bestselling author Thomas Erikson has helped changed how the world thinks about behavior using a simple 4-color behavior analysis system. In Surrounded by Bad Bosses he applies that same system to revolutionize the workplace.</p><p>Everyone has had a bad boss. You might have one right now. You might even be one. Bad bosses are a fact of the workplace, whether they’re short-tempered, unclear about expectations, or too disorganized to manage so much as a stapler. But how do you not only survive a difficult boss, but help your career thrive despite them?</p><p>By identifying your boss’s behavior profile you’ll be better able to interact with them no matter what the situation. Erikson offers example stories and concrete steps to help you thrive in any work situation.</p><p>Of course, much as we love to blame our bosses, sometimes management isn’t the problem at all. For every bad boss there is also a lazy employee, so Erikson also looks at the issue from a completely different perspective—employees themselves— and explores why some colleagues frequently underachieve, and what you can do to change this if you're the boss.</p>",
    yearOfPublishing: new Date("2020"),
    numberOfPages: 390,
    genre: "non-fiction",
  },
  {
    name: "Surrounded by Bad Bosses (And Lazy Employees)",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637519065/books/41p2MHIa_tL_h0mfvp.jpg"],
    quantity: 60,
    author: "619a8c932b77b7d09028ea9a",
    categories: "paper-books",
    currentPrice: 15,
    publisher: "martin-essentials",
    shortDescription: "Internationally bestselling author Thomas Erikson has helped changed how the world thinks about behavior using a simple 4-color behavior analysis system. In Surrounded by Bad Bosses he applies that same system to revolutionize the workplace.",
    fullDescription: "<p>Internationally bestselling author Thomas Erikson has helped changed how the world thinks about behavior using a simple 4-color behavior analysis system. In Surrounded by Bad Bosses he applies that same system to revolutionize the workplace.</p><p>Everyone has had a bad boss. You might have one right now. You might even be one. Bad bosses are a fact of the workplace, whether they’re short-tempered, unclear about expectations, or too disorganized to manage so much as a stapler. But how do you not only survive a difficult boss, but help your career thrive despite them?</p><p>By identifying your boss’s behavior profile you’ll be better able to interact with them no matter what the situation. Erikson offers example stories and concrete steps to help you thrive in any work situation.</p><p>Of course, much as we love to blame our bosses, sometimes management isn’t the problem at all. For every bad boss there is also a lazy employee, so Erikson also looks at the issue from a completely different perspective—employees themselves— and explores why some colleagues frequently underachieve, and what you can do to change this if you're the boss.</p>",
    yearOfPublishing: new Date("2020"),
    numberOfPages: 390,
    genre: "non-fiction",
    coverType: "hard"
  },
  {
    name: "Bring Me The Head Of The Taskmaster: 101 next-level tasks",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637521759/books/51Y4RMxbzOL._SX357_BO1_204_203_200__rtsdly.jpg"],
    quantity: 60,
    author: "619a97fb06cf40de5ced4b99",
    categories: "paper-books",
    currentPrice: 15,
    publisher: "ebury-publishing",
    shortDescription: "In the irresistible vein of the Taskmaster game show, this gloriously entertaining volume from Alex Horne serves up a shedload of missions to keep everyone entertained in the race to find The Taskmaster's Head.",
    fullDescription: "<p>Fastest wins. Your adventure starts now ...</p><p>This is a race.It is not a race against the clock, because that would be a far easier race. Clocks can be fast, but clocks never win races. It's nearly always humans, sometimes horses, and occasionally dogs. This is a race against your fellow Taskmaster players.</p><p>You are competing against everyone else who is reading this book. All you've got to do is find The Taskmaster's Head first. This is a race with many twists and turns, that requires very little running, much sideways thinking and quite a lot of patience.</p><p>Thankfully, there will be a shedload of tasks along the way to distract you. There are tasks to do on your own, tasks to do with your family and friends, and tasks for bigger groups too. Some of these distractions may slow you down, but some may help you get where you need to go. As always, enjoy them, do your best, make good choices.</p>",
    yearOfPublishing: new Date("2021"),
    numberOfPages: 240,
    genre: "non-fiction",
    coverType: "hard"
  },
  {
    name: "Bring Me The Head Of The Taskmaster: 101 next-level tasks",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637521759/books/51Y4RMxbzOL._SX357_BO1_204_203_200__rtsdly.jpg"],
    quantity: 60,
    author: "619a97fb06cf40de5ced4b99",
    categories: "ebooks",
    currentPrice: 10,
    publisher: "ebury-publishing",
    shortDescription: "In the irresistible vein of the Taskmaster game show, this gloriously entertaining volume from Alex Horne serves up a shedload of missions to keep everyone entertained in the race to find The Taskmaster's Head.",
    fullDescription: "<p>Fastest wins. Your adventure starts now ...</p><p>This is a race.It is not a race against the clock, because that would be a far easier race. Clocks can be fast, but clocks never win races. It's nearly always humans, sometimes horses, and occasionally dogs. This is a race against your fellow Taskmaster players.</p><p>You are competing against everyone else who is reading this book. All you've got to do is find The Taskmaster's Head first. This is a race with many twists and turns, that requires very little running, much sideways thinking and quite a lot of patience.</p><p>Thankfully, there will be a shedload of tasks along the way to distract you. There are tasks to do on your own, tasks to do with your family and friends, and tasks for bigger groups too. Some of these distractions may slow you down, but some may help you get where you need to go. As always, enjoy them, do your best, make good choices.</p>",
    yearOfPublishing: new Date("2021"),
    numberOfPages: 240,
    genre: "non-fiction"
  },
  {
    name: "Taskmaster: 220 Extraordinary Tasks for Ordinary People",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637521881/books/9781785944680_zpwrmu.jpg"],
    quantity: 60,
    author: "619a97fb06cf40de5ced4b99",
    categories: "ebooks",
    currentPrice: 10,
    publisher: "ebury-publishing",
    shortDescription: "In the TV show and on my marriage certificate, my job description is 'Taskmaster's Assistant'. That's what I do and it's an honour. I like Taskmaster a lot. And, of course, I love The Taskmaster. He's mountainous.",
    fullDescription: "<p>In the TV show and on my marriage certificate, my job description is 'Taskmaster's Assistant'. That's what I do and it's an honour. I like Taskmaster a lot. And, of course, I love The Taskmaster. He's mountainous.</p><p>If you feel in any way the same as me then you should enjoy this paperback version of the official Taskmaster book.</p><p>There are tasks for you, your friends and your family. There are new tasks, secret things and sneaky tricks. And there is one swear word. So it's almost exactly like being on the show.</p><p>Good luck. Make good choices. Let's do Him proud.</p>",
    yearOfPublishing: new Date("2019"),
    numberOfPages: 352,
    genre: "non-fiction"
  },
  {
    name: "Taskmaster: 220 Extraordinary Tasks for Ordinary People",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637521881/books/9781785944680_zpwrmu.jpg"],
    quantity: 60,
    author: "619a97fb06cf40de5ced4b99",
    categories: "paper-books",
    currentPrice: 15,
    publisher: "ebury-publishing",
    shortDescription: "In the TV show and on my marriage certificate, my job description is 'Taskmaster's Assistant'. That's what I do and it's an honour. I like Taskmaster a lot. And, of course, I love The Taskmaster. He's mountainous.",
    fullDescription: "<p>In the TV show and on my marriage certificate, my job description is 'Taskmaster's Assistant'. That's what I do and it's an honour. I like Taskmaster a lot. And, of course, I love The Taskmaster. He's mountainous.</p><p>If you feel in any way the same as me then you should enjoy this paperback version of the official Taskmaster book.</p><p>There are tasks for you, your friends and your family. There are new tasks, secret things and sneaky tricks. And there is one swear word. So it's almost exactly like being on the show.</p><p>Good luck. Make good choices. Let's do Him proud.</p>",
    yearOfPublishing: new Date("2019"),
    numberOfPages: 352,
    genre: "non-fiction",
    coverType: "hard",
  },
  {
    name: "The Wolf Den",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637522801/books/9781838933555_sqmjkg.jpg"],
    quantity: 20,
    author: "619a9cd662e0d8e5a0da8cae",
    categories: "paper-books",
    currentPrice: 10,
    publisher: "head-of-zeus",
    shortDescription: "Set in the seedy yet complex milieu of Pompeii’s brothels, Harper’s masterful first historical novel follows Amara and her fellow ‘she-wolves’ through a city where opportunity is rife for even the lowest born slave.",
    fullDescription: "<p>Sold by her mother. Enslaved in Pompeii's brothel. Determined to survive. Her name is Amara. Welcome to the Wolf Den...</p><p>Amara was once a beloved daughter, until her father's death plunged her family into penury. Now she is a slave in Pompeii's infamous brothel, owned by a man she despises. Sharp, clever and resourceful, Amara is forced to hide her talents. For now her only value lies in the desire she can stir in others.</p><p>But Amara's spirit is far from broken. By day, she walks the streets with the Wolf Den's other women, finding comfort in the laughter and dreams they share. For the streets of Pompeii are alive with opportunity. Out here, even the lowest slave can secure a reversal in fortune. Amara has learnt that everything in this city has its price. But how much is her freedom going to cost her?</p><p>Set in Pompeii's lupanar, The Wolf Den is the first in a trilogy of novels reimagining the lives of women who have long been overlooked. Perfect for fans of Pat Barker's The Silence of the Girls and Madeline Miller's Circe.</p>",
    yearOfPublishing: new Date("2021"),
    numberOfPages: 464,
    genre: "fiction",
    coverType: "soft",
  },
  {
    name: "The Wolf Den",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637522801/books/9781838933555_sqmjkg.jpg"],
    quantity: 200,
    author: "619a9cd662e0d8e5a0da8cae",
    categories: "audio-books",
    currentPrice: 5,
    publisher: "head-of-zeus",
    shortDescription: "Set in the seedy yet complex milieu of Pompeii’s brothels, Harper’s masterful first historical novel follows Amara and her fellow ‘she-wolves’ through a city where opportunity is rife for even the lowest born slave.",
    fullDescription: "<p>Sold by her mother. Enslaved in Pompeii's brothel. Determined to survive. Her name is Amara. Welcome to the Wolf Den...</p><p>Amara was once a beloved daughter, until her father's death plunged her family into penury. Now she is a slave in Pompeii's infamous brothel, owned by a man she despises. Sharp, clever and resourceful, Amara is forced to hide her talents. For now her only value lies in the desire she can stir in others.</p><p>But Amara's spirit is far from broken. By day, she walks the streets with the Wolf Den's other women, finding comfort in the laughter and dreams they share. For the streets of Pompeii are alive with opportunity. Out here, even the lowest slave can secure a reversal in fortune. Amara has learnt that everything in this city has its price. But how much is her freedom going to cost her?</p><p>Set in Pompeii's lupanar, The Wolf Den is the first in a trilogy of novels reimagining the lives of women who have long been overlooked. Perfect for fans of Pat Barker's The Silence of the Girls and Madeline Miller's Circe.</p>",
    yearOfPublishing: new Date("2021"),
    genre: "fiction",
    duration: 620
  },
  {
    name: "The House with the Golden Door",
    itemNo: rand(),
    imageUrls: ["https://res.cloudinary.com/dsdzwg97f/image/upload/v1637523116/books/9781838933579_cnsqfb.jpg"],
    quantity: 100,
    author: "619a9cd662e0d8e5a0da8cae",
    categories: "paper-books",
    currentPrice: 10,
    previousPrice: 13,
    publisher: "head-of-zeus",
    shortDescription: "Following on from the bestselling The Wolf Den, this second part of Harper's mesmerising trilogy set in ancient Pompeii sees Amara, now freed from slavery, navigate her new life which transpires to be no less precarious than before.",
    fullDescription: "<p>The life of a courtesan in Pompeii is glittering, yet precarious...</p><p>Amara has escaped her life as a slave in the town's most notorious brothel, but now her existence depends on the affections of her patron: a man she might not know as well as she once thought.</p><p>At night she dreams of the wolf den, still haunted by her past. Amara longs for the women she was forced to leave behind and worse, finds herself pursued by the man who once owned her. In order to be free, she will need to be as ruthless as he is.</p><p>Amara knows her existence in Pompeii is subject to Venus, the goddess of love. Yet finding love may prove to be the most dangerous act of all.</p><p>We return to Pompeii for the second instalment in Elodie Harper's Wolf Den Trilogy, set in the town's lupanar and reimagining the lives of women long overlooked.</p>",
    yearOfPublishing: new Date("2021"),
    numberOfPages: 400,
    genre: "fiction",
    coverType: "soft",
  },
  {
    name: "The House with the Golden Door",
    itemNo: rand(),
    quantity: 100,
    author: "619a9cd662e0d8e5a0da8cae",
    categories: "ebooks",
    currentPrice: 10,
    publisher: "head-of-zeus",
    shortDescription: "Following on from the bestselling The Wolf Den, this second part of Harper's mesmerising trilogy set in ancient Pompeii sees Amara, now freed from slavery, navigate her new life which transpires to be no less precarious than before.",
    fullDescription: "<p>The life of a courtesan in Pompeii is glittering, yet precarious...</p><p>Amara has escaped her life as a slave in the town's most notorious brothel, but now her existence depends on the affections of her patron: a man she might not know as well as she once thought.</p><p>At night she dreams of the wolf den, still haunted by her past. Amara longs for the women she was forced to leave behind and worse, finds herself pursued by the man who once owned her. In order to be free, she will need to be as ruthless as he is.</p><p>Amara knows her existence in Pompeii is subject to Venus, the goddess of love. Yet finding love may prove to be the most dangerous act of all.</p><p>We return to Pompeii for the second instalment in Elodie Harper's Wolf Den Trilogy, set in the town's lupanar and reimagining the lives of women long overlooked.</p>",
    yearOfPublishing: new Date("2021"),
    numberOfPages: 400,
    genre: "fiction"
  },
];