export const SET_GENRES = 'SET_GENRES';
export const SET_FORMATS = 'SET_FORMATS';
export const SET_MIN_PRICE = 'SET_MIN_PRICE';
export const SET_MAX_PRICE = 'SET_MAX_PRICE';
export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';
export const SET_SELECTED_AUTHOR = 'SET_SELECTED_AUTHOR';
export const SET_TOTAL_COUNT_OF_PAGES = 'SET_TOTAL_COUNT_OF_PAGES';
