export const SET_GENRES = 'SET_GENRES';
export const SET_FORMATS = 'SET_FORMATS';
export const SET_MIN_PRICE = 'SET_MIN_PRICE';
export const SET_MAX_PRICE = 'SET_MAX_PRICE';
export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const SET_SELECTED_GENRE = 'SET_SELECTED_GENRE';
